package pe.gob.sblm.sgi.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Adenda generated by hbm2java
 */
@Entity
@Table(name="ADENDA"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class Adenda implements java.io.Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer idadenda;
	private Contrato contrato;
	private Boolean sifinalizado;
	private String estado;
	private Integer nroadenda;
	private String observacionadenda;
	private Date iniciocontratoadenda;
	private Date fincontratoadenda;	
	private Date fincobrocontrato;
	private Date iniciocobroadenda;
	private Date fincobroadenda;
	private Date nuevofincontrato;
	private String usrcre;
	private Date feccre;
	private String usrmod;
	private Date fecmod;
	private String observacionmod;
	private Integer tipocondicionadenda;
	private String nombretipocondicion;
	private Boolean sidocumento;
	private String host_ip_usrcre;
	private String host_ip_usrmod;
	private String estado_doc;
	
	private Set<Detalleadenda> detalleadendas = new HashSet<Detalleadenda>(0);
	
	
	 public Adenda() {
		}
	 
	@Id 
     @GeneratedValue
    @Column(name="IDADENDA", unique=true, nullable=false)
	public Integer getIdadenda() {
		return idadenda;
	}
	public void setIdadenda(Integer idadenda) {
		this.idadenda = idadenda;
	}
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCONTRATO")
	public Contrato getContrato() {
		return contrato;
	}
	public void setContrato(Contrato contrato) {
		this.contrato = contrato;
	}
	 @Column(name="SIFINALIZADO")
	public Boolean getSifinalizado() {
			return sifinalizado;
	}
	public void setSifinalizado(Boolean sifinalizado) {
			this.sifinalizado = sifinalizado;
	}
	 @Column(name="ESTADO")
	 public String getEstado() {
		return estado;
	}
	public void setEstado(String estado) {
		this.estado = estado;
	}
	@Column(name="OBSERVACIONADENDA", length=200)
	public String getObservacionadenda() {
		return observacionadenda;
	}

	public void setObservacionadenda(String observacionadenda) {
		this.observacionadenda = observacionadenda;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="FINCONTRATOADENDA", length=23)
	public Date getFincontratoadenda() {
		return fincontratoadenda;
	}
	public void setFincontratoadenda(Date fincontratoadenda) {
		this.fincontratoadenda = fincontratoadenda;
	}
	 @Column(name="OBSERVACIONMOD", length=200)
	public String getObservacionmod() {
		return observacionmod;
	}
	public void setObservacionmod(String observacionmod) {
		this.observacionmod = observacionmod;
	}
	 @Column(name="USRCRE", length=50)
	public String getUsrcre() {
		return usrcre;
	}
	public void setUsrcre(String usrcre) {
		this.usrcre = usrcre;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="FECCRE", length=23)
	public Date getFeccre() {
		return feccre;
	}
	public void setFeccre(Date feccre) {
		this.feccre = feccre;
	}
	@Column(name="USRMOD", length=50)
	public String getUsrmod() {
		return usrmod;
	}
	public void setUsrmod(String usrmod) {
		this.usrmod = usrmod;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="FECMOD", length=23)
	public Date getFecmod() {
		return fecmod;
	}
	public void setFecmod(Date fecmod) {
		this.fecmod = fecmod;
	}
	@Column(name="NROADENDA")
	public Integer getNroadenda() {
		return nroadenda;
	}
	public void setNroadenda(Integer nroadenda) {
		this.nroadenda = nroadenda;
	}
	@Temporal(TemporalType.DATE)
	@Column(name="FINCOBROCONTRATO", length=10)
	public Date getFincobrocontrato() {
		return fincobrocontrato;
	}
	public void setFincobrocontrato(Date fincobrocontrato) {
		this.fincobrocontrato = fincobrocontrato;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="INICIOCONTRATOADENDA", length=23)
	public Date getIniciocontratoadenda() {
		return iniciocontratoadenda;
	}
	public void setIniciocontratoadenda(Date iniciocontratoadenda) {
		this.iniciocontratoadenda = iniciocontratoadenda;
	}
	@Temporal(TemporalType.DATE)
	@Column(name="INICIOCOBROADENDA", length=10)
	public Date getIniciocobroadenda() {
		return iniciocobroadenda;
	}

	public void setIniciocobroadenda(Date iniciocobroadenda) {
		this.iniciocobroadenda = iniciocobroadenda;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name="FINCOBROADENDA", length=10)
	public Date getFincobroadenda() {
		return fincobroadenda;
	}

	public void setFincobroadenda(Date fincobroadenda) {
		this.fincobroadenda = fincobroadenda;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="NUEVAFECHAFINCONTRATO", length=23)
	public Date getNuevofincontrato() {
		return nuevofincontrato;
	}


	public void setNuevofincontrato(Date nuevofincontrato) {
		this.nuevofincontrato = nuevofincontrato;
	}
	@Column(name="TIPOCONDICIONADENDA")
	public Integer getTipocondicionadenda() {
		return tipocondicionadenda;
	}
	public void setTipocondicionadenda(Integer tipocondicionadenda) {
		this.tipocondicionadenda = tipocondicionadenda;
	}
    @Column(name="NOMBRETIPOCONDICION")
	public String getNombretipocondicion() {
		return nombretipocondicion;
	}
	public void setNombretipocondicion(String nombretipocondicion) {
		this.nombretipocondicion = nombretipocondicion;
	}
	@Column(name="SIDOCUMENTO")
	public Boolean getSidocumento() {
		return sidocumento;
	}
	public void setSidocumento(Boolean sidocumento) {
		this.sidocumento = sidocumento;
	}
	@Column(name="HOST_IP_USRCRE")
	public String getHost_ip_usrcre() {
		return host_ip_usrcre;
	}

	public void setHost_ip_usrcre(String host_ip_usrcre) {
		this.host_ip_usrcre = host_ip_usrcre;
	}
	@Column(name="HOST_IP_USRMOD")
	public String getHost_ip_usrmod() {
		return host_ip_usrmod;
	}

	public void setHost_ip_usrmod(String host_ip_usrmod) {
		this.host_ip_usrmod = host_ip_usrmod;
	}
	@Column(name="ESTADO_DOC")
	public String getEstado_doc() {
		return estado_doc;
	}

	public void setEstado_doc(String estado_doc) {
		this.estado_doc = estado_doc;
	}

	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="adenda")
	public Set<Detalleadenda> getDetalleadendas() {
		return detalleadendas;
	}
	public void setDetalleadendas(Set<Detalleadenda> detalleadendas) {
		this.detalleadendas = detalleadendas;
	}
	
	
}
