package pe.gob.sblm.sgi.entity;

// Generated 09/01/2014 09:49:19 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Alerta generated by hbm2java
 */
@Entity
@Table(name = "ALERTA", schema = "dbo", catalog = "sisinmueble")
public class Alerta implements java.io.Serializable {

	private int idalerta;
	private Usuario usuario;
	private String mensaje;
	private Date fechaejecucion;
	private Boolean envioemail;
	private String usrcre;
	private String usrmod;
	private Date feccre;
	private Date fecmod;
	private Boolean envionotificacion;
	private Boolean estado;

	public Alerta() {
	}

	public Alerta(int idalerta) {
		this.idalerta = idalerta;
	}

	public Alerta(int idalerta, Usuario usuario, String mensaje,
			Date fechaejecucion, Boolean envioemail, String usrcre,
			String usrmod, Date feccre, Date fecmod, Boolean envionotificacion) {
		this.idalerta = idalerta;
		this.usuario = usuario;
		this.mensaje = mensaje;
		this.fechaejecucion = fechaejecucion;
		this.envioemail = envioemail;
		this.usrcre = usrcre;
		this.usrmod = usrmod;
		this.feccre = feccre;
		this.fecmod = fecmod;
		this.envionotificacion = envionotificacion;
	}

	@Id @GeneratedValue
	@Column(name = "IDALERTA", unique = true, nullable = false)
	public int getIdalerta() {
		return this.idalerta;
	}

	public void setIdalerta(int idalerta) {
		this.idalerta = idalerta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUSUARIO")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "MENSAJE", length = 500)
	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHAEJECUCION", length = 23)
	public Date getFechaejecucion() {
		return this.fechaejecucion;
	}

	public void setFechaejecucion(Date fechaejecucion) {
		this.fechaejecucion = fechaejecucion;
	}

	@Column(name = "ENVIOEMAIL")
	public Boolean getEnvioemail() {
		return this.envioemail;
	}

	public void setEnvioemail(Boolean envioemail) {
		this.envioemail = envioemail;
	}

	@Column(name = "USRCRE", length = 100)
	public String getUsrcre() {
		return this.usrcre;
	}

	public void setUsrcre(String usrcre) {
		this.usrcre = usrcre;
	}

	@Column(name = "USRMOD", length = 100)
	public String getUsrmod() {
		return this.usrmod;
	}

	public void setUsrmod(String usrmod) {
		this.usrmod = usrmod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECCRE", length = 23)
	public Date getFeccre() {
		return this.feccre;
	}

	public void setFeccre(Date feccre) {
		this.feccre = feccre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECMOD", length = 23)
	public Date getFecmod() {
		return this.fecmod;
	}

	public void setFecmod(Date fecmod) {
		this.fecmod = fecmod;
	}

	@Column(name = "ENVIONOTIFICACION")
	public Boolean getEnvionotificacion() {
		return this.envionotificacion;
	}

	public void setEnvionotificacion(Boolean envionotificacion) {
		this.envionotificacion = envionotificacion;
	}
	@Column(name = "ESTADO")
	public Boolean getEstado() {
		return estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}
	
	

}
