package pe.gob.sblm.sgi.entity;

// Generated 10/12/2013 10:50:12 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Archivodocumento generated by hbm2java
 */
@Entity
@Table(name = "ARCHIVO", schema = "dbo", catalog = "sisinmueble")
public class Archivo implements java.io.Serializable {

	private int idrepositorio;
	private String tipo;
	private String titulo;
	private String descripcion;
	private String observacion;
	private String uid;
	private int peso;
	private String uidAlfresco;
	private Inquilino inquilino;
	private Carta carta;
	private Inmueblemaestro inmueble;
	private Upa upa;
	private Arbitrio arbitrio;
	private Contrato contrato;
	private Date fechacreacion;
	private String usuariocreador;
	private Date fechamodificacion;
	private String usuariomodificador;
	private String nombre;
	private Procesojudicialupa procesojudicialupa;
	private Comprobantepago comprobantepago;

	public Archivo() {
	}

	public Archivo(int idrepositorio) {
		this.idrepositorio = idrepositorio;
	}


	@Id @GeneratedValue
	@Column(name = "IDARCHIVO", unique = true, nullable = false)
	public int getIdrepositorio() {
		return idrepositorio;
	}

	public void setIdrepositorio(int idrepositorio) {
		this.idrepositorio = idrepositorio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDINQUILINO")
	public Inquilino getInquilino() {
		return this.inquilino;
	}

	public void setInquilino(Inquilino inquilino) {
		this.inquilino = inquilino;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCARTA")
	public Carta getCarta() {
		return this.carta;
	}

	public void setCarta(Carta carta) {
		this.carta = carta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDINMUEBLE")
	public Inmueblemaestro getInmueble() {
		return inmueble;
	}

	public void setInmueble(Inmueblemaestro inmueble) {
		this.inmueble = inmueble;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUPA")
	public Upa getUpa() {
		return this.upa;
	}



	public void setUpa(Upa upa) {
		this.upa = upa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDARBITRIO")
	public Arbitrio getArbitrio() {
		return this.arbitrio;
	}

	public void setArbitrio(Arbitrio arbitrio) {
		this.arbitrio = arbitrio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCONTRATO")
	public Contrato getContrato() {
		return this.contrato;
	}

	public void setContrato(Contrato contrato) {
		this.contrato = contrato;
	}

	@Column(name = "TIPO", length = 5)
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "UID", length = 50)
	public String getUid() {
		return uid;
	}


	public void setUid(String uid) {
		this.uid = uid;
	}

	
	@Column(name = "UIDALFRESCO", length = 50)
	public String getUidAlfresco() {
		return uidAlfresco;
	}

	public void setUidAlfresco(String uidAlfresco) {
		this.uidAlfresco = uidAlfresco;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHACREACION", length = 23)
	public Date getFechacreacion() {
		return fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}
	
	@Column(name = "USUARIOCREADOR", length = 50)
	public String getUsuariocreador() {
		return usuariocreador;
	}

	public void setUsuariocreador(String usuariocreador) {
		this.usuariocreador = usuariocreador;
	}

	@Column(name = "FECHAMODIFICACION", length = 23)
	public Date getFechamodificacion() {
		return fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	@Column(name = "USUARIOMODIFICADOR", length = 50)
	public String getUsuariomodificador() {
		return usuariomodificador;
	}

	public void setUsuariomodificador(String usuariomodificador) {
		this.usuariomodificador = usuariomodificador;
	}

	@Column(name = "TITULO", length = 100)
	public String getTitulo() {
		return titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "DESCRIPCION", length = 200)
	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	@Column(name = "OBSERVACION", length = 1000)
	public String getObservacion() {
		return observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}
	
	@Column(name = "PESO", length = 20)
	public int getPeso() {
		return peso;
	}

	public void setPeso(int peso) {
		this.peso = peso;
	}
	
	@Column(name = "NOMBRE", length = 200)
	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPROCESOJUDICIALUPA")
	public Procesojudicialupa getProcesojudicialupa() {
		return procesojudicialupa;
	}

	public void setProcesojudicialupa(Procesojudicialupa procesojudicialupa) {
		this.procesojudicialupa = procesojudicialupa;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCOMPROBANTE")
	public Comprobantepago getComprobantepago() {
		return comprobantepago;
	}

	public void setComprobantepago(Comprobantepago comprobantepago) {
		this.comprobantepago = comprobantepago;
	}
    
     
}
