package pe.gob.sblm.sgi.entity;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Aud_Comprobantepago generated by hbm2java
 */
@Entity
@Table(name="AUD_COMPROBANTEPAGO"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class Aud_Comprobantepago {
    private int id_aud;
    private String accion_aud;
	private Comprobantepago comprobante;
	private Detallecartera detallecartera;
	private Tipodocu tipodocu;
    private Tipopago tipopago;
    private Tipomovimiento tipomovimiento;
    private String nroseriecomprobante;
    private String nroserie;
    private String nrocomprobante;
    private Double subtotalsoles;    
    private Double igvsoles;
    private Double totalsoles;
    private Double moradetectada;
    private Boolean sidetraccion;
    private Double montodetraccion;
    private String nombrecobrador;
    private String observacion;
    private Date fechaemision;
    private Date fechacancelacion;
    private Boolean sigeneronotadebito;
    private String nrocomprobantepadre;
    private Date fechacreacion;
    private String usuariocreador;
    private Date fechamodificacion;
    private String usuariomodificador;
    private Comprobantepago notadebito;
    private String nombrepagante;
    private Boolean sigeneronotacredito;
    private Tipocambio tipocambio;
    private Tipoconcepto tipoconcepto;
    private String dnirucpagante;
    private Comprobantepago notacredito; 
    private Igv igv;
    private Detraccion detraccion;
    private Boolean sianulado;
    private Usuario usuario;
    private String ipoperacion;
    private String mac_operacion;
    private Date fechavencimiento ;
    private Double tipcambio;
    private String numerooperacion;
    private Boolean sifacturacionelectronica;
    private String glosario;
    private Tipopersona tipopersona;
    private String obs_direccion;
    private String comp_opc;
    private String comp_concepto;
    private String tipodescuentonotacredito;
    private Boolean sigeneropenalizacion;
    private Double montopenalizacion; 
    private Comprobantepago notadebitopenalizacion;
    private Boolean sigeneronotacredito2;
    private Comprobantepago notacredito2;
    private Boolean siautodetraccion;
    private Double montoautodetraccion;
    
    
//  private Boolean sirecibocajausado;
//  private Double montorecibocajausado;
//  
//
//    
//  private Comprobantepago reciboCaja;
//  private String tipodescuentonotacredito;
//  private Boolean sifacturacionelectronica;
//  private Double tipcambio;
//  private Set<Detallecuota> detallecuotas = new HashSet<Detallecuota>(0);
//  private Set<Detallecuota_arbitrio> detallecuota_arbitrio = new HashSet<Detallecuota_arbitrio>(0);
//  private Date fechavencimiento;
//  private String numerooperacion;
//  private Boolean sigeneropenalizacion;
//  private Double montopenalizacion; 
//  private Comprobantepago notadebitopenalizacion;
//  private String glosario;
//  private String idtipopersona;
//  private String obs_direccion;
//  private String comp_concepto;
//  private String comp_opc;
//  private Boolean sigeneronotacredito2;
//  private Comprobantepago notacredito2;
//  private Boolean siautodetraccion;
//  private Double montoautodetraccion;
    public Aud_Comprobantepago() {
		
	}
    
    @Id
    @GeneratedValue
    @Column(name="ID_AUD",unique=true, nullable=false)
	public int getId_aud() {
		return id_aud;
	}	
	public void setId_aud(int id_aud) {
		this.id_aud = id_aud;
	}
	
	@Column(name="ACCION_AUD",length=6)
	public String getAccion_aud() {
		return accion_aud;
	}
	public void setAccion_aud(String accion_aud) {
		this.accion_aud = accion_aud;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="IDCOMPROBANTE")
	public Comprobantepago getComprobante() {
		return comprobante;
	}
	public void setComprobante(Comprobantepago comprobante) {
		this.comprobante = comprobante;
	}
	
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDDETALLECARTERA")
	public Detallecartera getDetallecartera() {
		return detallecartera;
	}
	public void setDetallecartera(Detallecartera detallecartera) {
		this.detallecartera = detallecartera;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="IDTIPODOCU")
	public Tipodocu getTipodocu() {
		return tipodocu;
	}
	public void setTipodocu(Tipodocu tipodocu) {
		this.tipodocu = tipodocu;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="IDTIPOPAGO")
	public Tipopago getTipopago() {
		return tipopago;
	}
	public void setTipopago(Tipopago tipopago) {
		this.tipopago = tipopago;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="IDTIPOMOVIMIENTO")
	public Tipomovimiento getTipomovimiento() {
		return tipomovimiento;
	}
	public void setTipomovimiento(Tipomovimiento tipomovimiento) {
		this.tipomovimiento = tipomovimiento;
	}
	
	@Column(name="NROSERIECOMPROBANTE", length=30)
	public String getNroseriecomprobante() {
		return nroseriecomprobante;
	}
	public void setNroseriecomprobante(String nroseriecomprobante) {
		this.nroseriecomprobante = nroseriecomprobante;
	}
	
	@Column(name="NROSERIE",length=10)
	public String getNroserie() {
		return nroserie;
	}
	public void setNroserie(String nroserie) {
		this.nroserie = nroserie;
	}
	
	@Column(name="NROCOMPROBANTE", length=20)
	public String getNrocomprobante() {
		return nrocomprobante;
	}
	public void setNrocomprobante(String nrocomprobante) {
		this.nrocomprobante = nrocomprobante;
	}
	
	@Column(name="SUBTOTALSOLES",precision=53 , scale=0)
	public Double getSubtotalsoles() {
		return subtotalsoles;
	}
	public void setSubtotalsoles(Double subtotalsoles) {
		this.subtotalsoles = subtotalsoles;
	}
	
	@Column(name="IGVSOLES",precision=53 , scale=0)
	public Double getIgvsoles() {
		return igvsoles;
	}
	public void setIgvsoles(Double igvsoles) {
		this.igvsoles = igvsoles;
	}
	
	@Column(name="TOTALSOLES",precision=53 , scale=0)
	public Double getTotalsoles() {
		return totalsoles;
	}
	public void setTotalsoles(Double totalsoles) {
		this.totalsoles = totalsoles;
	}
	
	@Column(name="MORADETECTADA",precision=53 , scale=0)
	public Double getMoradetectada() {
		return moradetectada;
	}
	public void setMoradetectada(Double moradetectada) {
		this.moradetectada = moradetectada;
	}
	
	@Column(name="SIDETRACCION")
	public Boolean getSidetraccion() {
		return sidetraccion;
	}
	public void setSidetraccion(Boolean sidetraccion) {
		this.sidetraccion = sidetraccion;
	}
	
	@Column(name="MONTODETRACCION", precision=53, scale=0)
	public Double getMontodetraccion() {
		return montodetraccion;
	}
	public void setMontodetraccion(Double montodetraccion) {
		this.montodetraccion = montodetraccion;
	}
	
	@Column(name="NOMBRECOBRADOR", length=150)
	public String getNombrecobrador() {
		return nombrecobrador;
	}
	public void setNombrecobrador(String nombrecobrador) {
		this.nombrecobrador = nombrecobrador;
	}
	
	@Column(name="OBSERVACION", length=150)
	public String getObservacion() {
		return observacion;
	}
	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAEMISION", length=23)
	public Date getFechaemision() {
		return fechaemision;
	}
	public void setFechaemision(Date fechaemision) {
		this.fechaemision = fechaemision;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHACANCELACION", length=23)
	public Date getFechacancelacion() {
		return fechacancelacion;
	}
	public void setFechacancelacion(Date fechacancelacion) {
		this.fechacancelacion = fechacancelacion;
	}
	
	@Column(name="SIGENERONOTADEBITO")
	public Boolean getSigeneronotadebito() {
		return sigeneronotadebito;
	}
	public void setSigeneronotadebito(Boolean sigeneronotadebito) {
		this.sigeneronotadebito = sigeneronotadebito;
	}
	
	@Column(name="NROCOMPROBANTEPADRE", length=20)
	public String getNrocomprobantepadre() {
		return nrocomprobantepadre;
	}
	public void setNrocomprobantepadre(String nrocomprobantepadre) {
		this.nrocomprobantepadre = nrocomprobantepadre;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHACREACION", length=23)
	public Date getFechacreacion() {
		return fechacreacion;
	}
	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}
	
	@Column(name="USUARIOCREADOR", length=100)
	public String getUsuariocreador() {
		return usuariocreador;
	}
	public void setUsuariocreador(String usuariocreador) {
		this.usuariocreador = usuariocreador;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAMODIFICACION", length=23)
	public Date getFechamodificacion() {
		return fechamodificacion;
	}
	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}
	
    @Column(name="USUARIOMODIFICADOR", length=100)
	public String getUsuariomodificador() {
		return usuariomodificador;
	}
	public void setUsuariomodificador(String usuariomodificador) {
		this.usuariomodificador = usuariomodificador;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDNOTADEBITO")
	public Comprobantepago getNotadebito() {
		return notadebito;
	}
	public void setNotadebito(Comprobantepago notadebito) {
		this.notadebito = notadebito;
	}
	
	@Column(name="NOMBREPAGANTE", length=100)
	public String getNombrepagante() {
		return nombrepagante;
	}
	public void setNombrepagante(String nombrepagante) {
		this.nombrepagante = nombrepagante;
	}
	
	@Column(name="SIGENERONOTACREDITO") 
	public Boolean getSigeneronotacredito() {
		return sigeneronotacredito;
	}
	public void setSigeneronotacredito(Boolean sigeneronotacredito) {
		this.sigeneronotacredito = sigeneronotacredito;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="IDTIPOCAMBIO")
	public Tipocambio getTipocambio() {
		return tipocambio;
	}
	public void setTipocambio(Tipocambio tipocambio) {
		this.tipocambio = tipocambio;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPOCONCEPTO")
	public Tipoconcepto getTipoconcepto() {
		return tipoconcepto;
	}
	public void setTipoconcepto(Tipoconcepto tipoconcepto) {
		this.tipoconcepto = tipoconcepto;
	}
	
	@Column(name="DNIRUCPAGANTE", length=11)
	public String getDnirucpagante() {
		return dnirucpagante;
	}
	public void setDnirucpagante(String dnirucpagante) {
		this.dnirucpagante = dnirucpagante;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDNOTACREDITO")
	public Comprobantepago getNotacredito() {
		return notacredito;
	}
	public void setNotacredito(Comprobantepago notacredito) {
		this.notacredito = notacredito;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDIGV")
	public Igv getIgv() {
		return igv;
	}
	public void setIgv(Igv igv) {
		this.igv = igv;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDDETRACCION")
	public Detraccion getDetraccion() {
		return detraccion;
	}
	public void setDetraccion(Detraccion detraccion) {
		this.detraccion = detraccion;
	}
	
	@Column(name="SIANULADO")
	public Boolean getSianulado() {
		return sianulado;
	}
	public void setSianulado(Boolean sianulado) {
		this.sianulado = sianulado;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDUSUARIO")
	public Usuario getUsuario() {
		return usuario;
	}
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	
	@Column(name="IP_OPERACION")
	public String getIpoperacion() {
		return ipoperacion;
	}
	public void setIpoperacion(String ipoperacion) {
		this.ipoperacion = ipoperacion;
	}
	
	@Column(name="MAC_OPERACION")
	public String getMac_operacion() {
		return mac_operacion;
	}
	public void setMac_operacion(String mac_operacion) {
		this.mac_operacion = mac_operacion;
	}
    
	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAVENCIMIENTO", length=23)
	public Date getFechavencimiento() {
		return fechavencimiento;
	}

	public void setFechavencimiento(Date fechavencimiento) {
		this.fechavencimiento = fechavencimiento;
	}
	
	@Column(name="TIPOCAMBIO", precision=53, scale=0)
	public Double getTipcambio() {
		return tipcambio;
	}

	public void setTipcambio(Double tipcambio) {
		this.tipcambio = tipcambio;
	}
    
	@Column(name="NUMEROOPERACION")
	public String getNumerooperacion() {
		return numerooperacion;
	}

	public void setNumerooperacion(String numerooperacion) {
		this.numerooperacion = numerooperacion;
	}

	@Column(name="SIFACTURACIONELECTRONICA")
	public Boolean getSifacturacionelectronica() {
		return sifacturacionelectronica;
	}

	public void setSifacturacionelectronica(Boolean sifacturacionelectronica) {
		this.sifacturacionelectronica = sifacturacionelectronica;
	}
    
	@Column(name="GLOSARIO", length=300)
	public String getGlosario() {
		return glosario;
	}

	public void setGlosario(String glosario) {
		this.glosario = glosario;
	}
    
	@Column(name="IDTIPOPERSONA")
	public Tipopersona getTipopersona() {
		return tipopersona;
	}

	public void setTipopersona(Tipopersona tipopersona) {
		this.tipopersona = tipopersona;
	}
    
	@Column(name="OBS_DIRECCION", length=300)
	public String getObs_direccion() {
		return obs_direccion;
	}

	public void setObs_direccion(String obs_direccion) {
		this.obs_direccion = obs_direccion;
	}
    
	@Column(name="COMP_OPC", length=1)
	public String getComp_opc() {
		return comp_opc;
	}

	public void setComp_opc(String comp_opc) {
		this.comp_opc = comp_opc;
	}
    
	@Column(name="COMP_CONCEPTO", length=300)
	public String getComp_concepto() {
		return comp_concepto;
	}

	public void setComp_concepto(String comp_concepto) {
		this.comp_concepto = comp_concepto;
	}
    
	@Column(name="TIPODESCUENTONOTACREDITO", length=10)
	public String getTipodescuentonotacredito() {
		return tipodescuentonotacredito;
	}

	public void setTipodescuentonotacredito(String tipodescuentonotacredito) {
		this.tipodescuentonotacredito = tipodescuentonotacredito;
	}
    
	@Column(name="SIGENEROPENALIZACION")
	public Boolean getSigeneropenalizacion() {
		return sigeneropenalizacion;
	}

	public void setSigeneropenalizacion(Boolean sigeneropenalizacion) {
		this.sigeneropenalizacion = sigeneropenalizacion;
	}
    
	@Column(name="MONTOPENALIZACION", precision=53, scale=0)
	public Double getMontopenalizacion() {
		return montopenalizacion;
	}

	public void setMontopenalizacion(Double montopenalizacion) {
		this.montopenalizacion = montopenalizacion;
	}
    
	@Column(name="IDNOTADEBITOPENALIZACION", nullable=true)
	public Comprobantepago getNotadebitopenalizacion() {
		return notadebitopenalizacion;
	}

	public void setNotadebitopenalizacion(Comprobantepago notadebitopenalizacion) {
		this.notadebitopenalizacion = notadebitopenalizacion;
	}
     
	@Column(name="SIGENERONOTACREDITO2")
	public Boolean getSigeneronotacredito2() {
		return sigeneronotacredito2;
	}

	public void setSigeneronotacredito2(Boolean sigeneronotacredito2) {
		this.sigeneronotacredito2 = sigeneronotacredito2;
	}
    
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDNOTACREDITO2")
	public Comprobantepago getNotacredito2() {
		return notacredito2;
	}

	public void setNotacredito2(Comprobantepago notacredito2) {
		this.notacredito2 = notacredito2;
	}
    
	@Column(name="SIAUTODETRACCION")	
	public Boolean getSiautodetraccion() {
		return siautodetraccion;
	}

	public void setSiautodetraccion(Boolean siautodetraccion) {
		this.siautodetraccion = siautodetraccion;
	}
    
	@Column(name="MONTOAUTODETRACCION", precision=53, scale=0)
	public Double getMontoautodetraccion() {
		return montoautodetraccion;
	}

	public void setMontoautodetraccion(Double montoautodetraccion) {
		this.montoautodetraccion = montoautodetraccion;
	}
        
	
}
