package pe.gob.sblm.sgi.entity;
// Generated 25/08/2014 09:36:23 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comprobantepago generated by hbm2java
 */
@Entity
@Table(name="COMPROBANTEPAGO"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class Comprobantepago  implements java.io.Serializable {
      
     private int idcomprobante;
     private Tipomovimiento tipomovimiento;
     private Tipodocu tipodocu;
     private Tipocambio tipocambio;
     private Detraccion detraccion;
     private Usuario usuario;
     private Igv igv;
     private Tipoconcepto tipoconcepto;
     private Detallecartera detallecartera;
     private Tipopago tipopago;
     private Date fechaemision;
     private String nroserie;
     private String nrocomprobante;
     private String observacion;
     private Double subtotalsoles;
     private Double totalsoles;
     private Double igvsoles;
     private String nrocomprobantepadre;
     private String nombrecobrador;
     private Date fechacreacion;
     private String usuariocreador;
     private Date fechamodificacion;
     private String usuariomodificador;
     private Date fechacancelacion;
     private Double moradetectada;
     private Boolean sigeneronotadebito;
     private String nroseriecomprobante;
     private Double montodetraccion;
     private Boolean sidetraccion;
     private String nombrepagante;
     private String dnirucpagante;
     private Boolean sigeneronotacredito;
     private Boolean sianulado;
     private Boolean sirecibocajausado;
     private Double montorecibocajausado;
     private Comprobantepago notadebito;
     private String ipoperacion;
//     private String mac_operacion;
     private Comprobantepago notacredito;    
     private Comprobantepago reciboCaja;
     private String tipodescuentonotacredito;
     private Boolean sifacturacionelectronica;
     private Double tipcambio;
     private Set<Detallecuota> detallecuotas = new HashSet<Detallecuota>(0);
     private Set<Detallecuota_arbitrio> detallecuota_arbitrio = new HashSet<Detallecuota_arbitrio>(0);
     private Date fechavencimiento;
     private String numerooperacion;
     private Boolean sigeneropenalizacion;
     private Double montopenalizacion; 
     private Comprobantepago notadebitopenalizacion;
     private String glosario;
     private String idtipopersona;
     private String obs_direccion;
     private String comp_concepto;
     private String comp_opc;
     private Boolean sigeneronotacredito2;
     private Comprobantepago notacredito2;
     private Boolean siautodetraccion;
     private Double montoautodetraccion;
     private Tipotransaccion tipotransaccion;
     //Anulacion
     private String usuario_anula_documento;
     private Date fecha_anula_documento;
     private String host_ip_anula_documento;
     private String descripcion_baja;
     private String estado;
     private String condicion;
     private Tipomodalidadpago tipomodalidadpago;
     private String nombreusr_cre;
     private String nombreusr_mod;
     private String textoimportetotal;
     private String comp_descripcionitem;
     private Boolean sidocumento;
     private String tipodoc_receptor;
     private Comprobantepago comprobanteref;



	public Comprobantepago() {
    }
    
	
     public Comprobantepago(int idcomprobante) {
		this.idcomprobante = idcomprobante;
	}


	@Id 
     @GeneratedValue
    @Column(name="IDCOMPROBANTE", unique=true, nullable=false)
    public int getIdcomprobante() {
        return this.idcomprobante;
    }
    
    public void setIdcomprobante(int idcomprobante) {
        this.idcomprobante = idcomprobante;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPOMOVIMIENTO")
    public Tipomovimiento getTipomovimiento() {
        return this.tipomovimiento;
    }
    
    public void setTipomovimiento(Tipomovimiento tipomovimiento) {
        this.tipomovimiento = tipomovimiento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPODOCU")
    public Tipodocu getTipodocu() {
        return this.tipodocu;
    }
    
    public void setTipodocu(Tipodocu tipodocu) {
        this.tipodocu = tipodocu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDDETALLECARTERA")
    public Detallecartera getDetallecartera() {
        return this.detallecartera;
    }
    
    public void setDetallecartera(Detallecartera detallecartera) {
        this.detallecartera = detallecartera;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPOPAGO")
    public Tipopago getTipopago() {
        return this.tipopago;
    }
    
    public void setTipopago(Tipopago tipopago) {
        this.tipopago = tipopago;
    }
    
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPOCAMBIO")
    public Tipocambio getTipocambio() {
		return tipocambio;
	}
	public void setTipocambio(Tipocambio tipocambio) {
		this.tipocambio = tipocambio;
	}
	
	
	
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDUSUARIO")	
    public Usuario getUsuario() {
		return usuario;
	}


	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}


	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDDETRACCION")
	public Detraccion getDetraccion() {
		return detraccion;
	}


	public void setDetraccion(Detraccion detraccion) {
		this.detraccion = detraccion;
	}

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDIGV")
	public Igv getIgv() {
		return igv;
	}


	public void setIgv(Igv igv) {
		this.igv = igv;
	}


	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPOCONCEPTO")
	public Tipoconcepto getTipoconcepto() {
		return tipoconcepto;
	}


	public void setTipoconcepto(Tipoconcepto tipoconcepto) {
		this.tipoconcepto = tipoconcepto;
	}


	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAEMISION", length=23)
    public Date getFechaemision() {
        return this.fechaemision;
    }
    
    public void setFechaemision(Date fechaemision) {
        this.fechaemision = fechaemision;
    }

    
    @Column(name="NROSERIE", length=10)
    public String getNroserie() {
        return this.nroserie;
    }
    
    public void setNroserie(String nroserie) {
        this.nroserie = nroserie;
    }

    
    @Column(name="NROCOMPROBANTE", length=20)
    public String getNrocomprobante() {
        return this.nrocomprobante;
    }
    
    public void setNrocomprobante(String nrocomprobante) {
        this.nrocomprobante = nrocomprobante;
    }

    
    @Column(name="OBSERVACION", length=1000)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="SUBTOTALSOLES", precision=53, scale=0)
    public Double getSubtotalsoles() {
        return this.subtotalsoles;
    }
    
    public void setSubtotalsoles(Double subtotalsoles) {
        this.subtotalsoles = subtotalsoles;
    }
    
    @Column(name="TOTALSOLES", precision=53, scale=0)
    public Double getTotalsoles() {
        return this.totalsoles;
    }
    
    public void setTotalsoles(Double totalsoles) {
        this.totalsoles = totalsoles;
    }

    @Column(name="IGVSOLES", precision=53, scale=0)
    public Double getIgvsoles() {
        return this.igvsoles;
    }
    
    public void setIgvsoles(Double igvsoles) {
        this.igvsoles = igvsoles;
    }
    
    @Column(name="NROCOMPROBANTEPADRE", length=20)
    public String getNrocomprobantepadre() {
        return this.nrocomprobantepadre;
    }
    
    public void setNrocomprobantepadre(String nrocomprobantepadre) {
        this.nrocomprobantepadre = nrocomprobantepadre;
    }

    
    @Column(name="NOMBRECOBRADOR", length=150)
    public String getNombrecobrador() {
        return this.nombrecobrador;
    }
    
    public void setNombrecobrador(String nombrecobrador) {
        this.nombrecobrador = nombrecobrador;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHACREACION", length=23)
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }

    
    @Column(name="USUARIOCREADOR", length=100)
    public String getUsuariocreador() {
        return this.usuariocreador;
    }
    
    public void setUsuariocreador(String usuariocreador) {
        this.usuariocreador = usuariocreador;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAMODIFICACION", length=23)
    public Date getFechamodificacion() {
        return this.fechamodificacion;
    }
    
    public void setFechamodificacion(Date fechamodificacion) {
        this.fechamodificacion = fechamodificacion;
    }

    
    @Column(name="USUARIOMODIFICADOR", length=100)
    public String getUsuariomodificador() {
        return this.usuariomodificador;
    }
    
    public void setUsuariomodificador(String usuariomodificador) {
        this.usuariomodificador = usuariomodificador;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHACANCELACION", length=23)
    public Date getFechacancelacion() {
        return this.fechacancelacion;
    }
    
    public void setFechacancelacion(Date fechacancelacion) {
        this.fechacancelacion = fechacancelacion;
    }

    
    @Column(name="MORADETECTADA", precision=53, scale=0)
    public Double getMoradetectada() {
        return this.moradetectada;
    }
    
    public void setMoradetectada(Double moradetectada) {
        this.moradetectada = moradetectada;
    }
    
    
    @Column(name="TIPOCAMBIO", precision=53, scale=0)
    public Double getTipcambio() {
		return tipcambio;
	}


	public void setTipcambio(Double tipcambio) {
		this.tipcambio = tipcambio;
	}


	@Column(name="MONTOUSADORECIBOCAJA", precision=53, scale=0)   
    public Double getMontorecibocajausado() {
		return montorecibocajausado;
	}


	public void setMontorecibocajausado(Double montorecibocajausado) {
		this.montorecibocajausado = montorecibocajausado;
	}


	@Column(name="SIGENERONOTADEBITO")
    public Boolean getSigeneronotadebito() {
        return this.sigeneronotadebito;
    }
    
    public void setSigeneronotadebito(Boolean sigeneronotadebito) {
        this.sigeneronotadebito = sigeneronotadebito;
    }

    
    @Column(name="SIGENERONOTACREDITO")   
    public Boolean getSigeneronotacredito() {
		return sigeneronotacredito;
	}


	public void setSigeneronotacredito(Boolean sigeneronotacredito) {
		this.sigeneronotacredito = sigeneronotacredito;
	}
    @Column(name="SIGENERONOTACREDITO2")   
    public Boolean getSigeneronotacredito2() {
		return sigeneronotacredito2;
	}


	public void setSigeneronotacredito2(Boolean sigeneronotacredito2) {
		this.sigeneronotacredito2 = sigeneronotacredito2;
	}

	@Column(name="NROSERIECOMPROBANTE", length=30)
    public String getNroseriecomprobante() {
        return this.nroseriecomprobante;
    }
    
    public void setNroseriecomprobante(String nroseriecomprobante) {
        this.nroseriecomprobante = nroseriecomprobante;
    }

    
    @Column(name="MONTODETRACCION", precision=53, scale=0)
    public Double getMontodetraccion() {
        return this.montodetraccion;
    }
    
    public void setMontodetraccion(Double montodetraccion) {
        this.montodetraccion = montodetraccion;
    }

    
    @Column(name="SIDETRACCION")
    public Boolean getSidetraccion() {
        return this.sidetraccion;
    }
    
    public void setSidetraccion(Boolean sidetraccion) {
        this.sidetraccion = sidetraccion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comprobantepago")
    public Set<Detallecuota> getDetallecuotas() {
        return this.detallecuotas;
    }
    
    public void setDetallecuotas(Set<Detallecuota> detallecuotas) {
        this.detallecuotas = detallecuotas;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDNOTADEBITO")
    public Comprobantepago getNotadebito() {
		return notadebito;
	}
	public void setNotadebito(Comprobantepago notadebito) {
		this.notadebito = notadebito;
	}
	
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDNOTACREDITO")
	public Comprobantepago getNotacredito() {
		return notacredito;
	}

	public void setNotacredito(Comprobantepago notacredito) {
		this.notacredito = notacredito;
	}
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCOMPROBANTEREF")
	public Comprobantepago getComprobanteref() {
		return comprobanteref;
	}

	public void setComprobanteref(Comprobantepago comprobanteref) {
		this.comprobanteref = comprobanteref;
	}
	
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDNOTACREDITO2")
	public Comprobantepago getNotacredito2() {
		return notacredito2;
	}

	public void setNotacredito2(Comprobantepago notacredito2) {
		this.notacredito2 = notacredito2;
	}
	

	/**
	 * @return the tipodescuentonotacredito
	 */
	@Column(name="TIPODESCUENTONOTACREDITO", length=10)
	public String getTipodescuentonotacredito() {
		return tipodescuentonotacredito;
	}


	/**
	 * @param tipodescuentonotacredito the tipodescuentonotacredito to set
	 */

	public void setTipodescuentonotacredito(String tipodescuentonotacredito) {
		this.tipodescuentonotacredito = tipodescuentonotacredito;
	}


	@Column(name="NOMBREPAGANTE", length=100)
	public String getNombrepagante() {
		return nombrepagante;
	}
	public void setNombrepagante(String nombrepagante) {
		this.nombrepagante = nombrepagante;
	}

	@Column(name="DNIRUCPAGANTE", length=11)
	public String getDnirucpagante() {
		return dnirucpagante;
	}


	public void setDnirucpagante(String dnirucpagante) {
		this.dnirucpagante = dnirucpagante;
	}

    @Column(name="SIANULADO")
	public Boolean getSianulado() {
		return sianulado;
	}


	public void setSianulado(Boolean sianulado) {
		this.sianulado = sianulado;
	}
	
	
    @Column(name="SIRECIBOCAJAUSADO")
    public Boolean getSirecibocajausado() {
		return sirecibocajausado;
	}


	public void setSirecibocajausado(Boolean sirecibocajausado) {
		this.sirecibocajausado = sirecibocajausado;
	}


	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDRECIBOCAJA")
	public Comprobantepago getReciboCaja() {
		return reciboCaja;
	}

	public void setReciboCaja(Comprobantepago reciboCaja) {
		this.reciboCaja = reciboCaja;
	}

    @Column(name="SIFACTURACIONELECTRONICA")
	public Boolean getSifacturacionelectronica() {
		return sifacturacionelectronica;
	}


	public void setSifacturacionelectronica(Boolean sifacturacionelectronica) {
		this.sifacturacionelectronica = sifacturacionelectronica;
	}

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAVENCIMIENTO", length=23)
	public Date getFechavencimiento() {
		return fechavencimiento;
	}


	public void setFechavencimiento(Date fechavencimiento) {
		this.fechavencimiento = fechavencimiento;
	}

    @Column(name="IP_OPERACION")
	public String getIpoperacion() {
		return ipoperacion;
	}


	public void setIpoperacion(String ipoperacion) {
		this.ipoperacion = ipoperacion;
	}

	@Column(name="NUMEROOPERACION")
	public String getNumerooperacion() {
		return numerooperacion;
	}


	public void setNumerooperacion(String numerooperacion) {
		this.numerooperacion = numerooperacion;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="comprobantepago")
	public Set<Detallecuota_arbitrio> getDetallecuota_arbitrio() {
		return detallecuota_arbitrio;
	}


	public void setDetallecuota_arbitrio(
			Set<Detallecuota_arbitrio> detallecuota_arbitrio) {
		this.detallecuota_arbitrio = detallecuota_arbitrio;
	}

	 @Column(name="SIGENEROPENALIZACION") 
	public Boolean getSigeneropenalizacion() {
		return sigeneropenalizacion;
	}


	public void setSigeneropenalizacion(Boolean sigeneropenalizacion) {
		this.sigeneropenalizacion = sigeneropenalizacion;
	}

	@Column(name="MONTOPENALIZACION", precision=53, scale=0)
	public Double getMontopenalizacion() {
		return montopenalizacion;
	}


	public void setMontopenalizacion(Double montopenalizacion) {
		this.montopenalizacion = montopenalizacion;
	}

//	@Column(name="IDNOTADEBITOPENALIZACION", nullable=true)
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDNOTADEBITOPENALIZACION")
	public Comprobantepago getNotadebitopenalizacion() {
		return notadebitopenalizacion;
	}


	public void setNotadebitopenalizacion(Comprobantepago notadebitopenalizacion) {
		this.notadebitopenalizacion = notadebitopenalizacion;
	}
//	public int getIdnotadebitopenalizacion() {
//		return idnotadebitopenalizacion;
//	}
//
//
//	public void setIdnotadebitopenalizacion(int idnotadebitopenalizacion) {
//		this.idnotadebitopenalizacion = idnotadebitopenalizacion;
//	}
//    

	@Column(name="GLOSARIO", length=300)
	public String getGlosario() {
		return glosario;
	}


	public void setGlosario(String glosario) {
		this.glosario = glosario;
	}
	@Column(name="IDTIPOPERSONA")
    public String getIdtipopersona() {
		return idtipopersona;
	}


	public void setIdtipopersona(String idtipopersona) {
		this.idtipopersona = idtipopersona;
	}

	@Column(name="OBS_DIRECCION", length=300)
	public String getObs_direccion() {
		return obs_direccion;
	}


	public void setObs_direccion(String obs_direccion) {
		this.obs_direccion = obs_direccion;
	}

	@Column(name="COMP_CONCEPTO", length=300)
	public String getComp_concepto() {
		return comp_concepto;
	}


	public void setComp_concepto(String comp_concepto) {
		this.comp_concepto = comp_concepto;
	}

	@Column(name="COMP_OPC", length=1)
	public String getComp_opc() {
		return comp_opc;
	}


	public void setComp_opc(String comp_opc) {
		this.comp_opc = comp_opc;
	}

	@Column(name="SIAUTODETRACCION")	
	public Boolean getSiautodetraccion() {
		return siautodetraccion;
	}


	public void setSiautodetraccion(Boolean siautodetraccion) {
		this.siautodetraccion = siautodetraccion;
	}

	@Column(name="MONTOAUTODETRACCION", precision=53, scale=0)
	public Double getMontoautodetraccion() {
		return montoautodetraccion;
	}

    
	public void setMontoautodetraccion(Double montoautodetraccion) {
		this.montoautodetraccion = montoautodetraccion;
	}

	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPOTRANSACCION")
	public Tipotransaccion getTipotransaccion() {
		return tipotransaccion;
	}


	public void setTipotransaccion(Tipotransaccion tipotransaccion) {
		this.tipotransaccion = tipotransaccion;
	}
  
    @Column(name="USUARIO_ANULA_DOCUMENTO")
	public String getUsuario_anula_documento() {
		return usuario_anula_documento;
	}


	public void setUsuario_anula_documento(String usuario_anula_documento) {
		this.usuario_anula_documento = usuario_anula_documento;
	}
    
	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHA_ANULA_DOCUMENTO",length=23)
	public Date getFecha_anula_documento() {
		return fecha_anula_documento;
	}


	public void setFecha_anula_documento(Date fecha_anula_documento) {
		this.fecha_anula_documento = fecha_anula_documento;
	}

    @Column(name="HOST_IP_ANULA_DOCUMENTO")
	public String getHost_ip_anula_documento() {
		return host_ip_anula_documento;
	}


	public void setHost_ip_anula_documento(String host_ip_anula_documento) {
		this.host_ip_anula_documento = host_ip_anula_documento;
	}

    @Column(name="DESCRIPCION_BAJA")
	public String getDescripcion_baja() {
		return descripcion_baja;
	}


	public void setDescripcion_baja(String descripcion_baja) {
		this.descripcion_baja = descripcion_baja;
	}

    @Column(name="ESTADO")
	public String getEstado() {
		return estado;
	}


	public void setEstado(String estado) {
		this.estado = estado;
	}

    @Column(name="CONDICION")
	public String getCondicion() {
		return condicion;
	}


	public void setCondicion(String condicion) {
		this.condicion = condicion;
	}

	@Column(name="NOMBREUSR_CRE")
	public String getNombreusr_cre() {
		return nombreusr_cre;
	}


	public void setNombreusr_cre(String nombreusr_cre) {
		this.nombreusr_cre = nombreusr_cre;
	}

	@Column(name="NOMBREUSR_MOD")
	public String getNombreusr_mod() {
		return nombreusr_mod;
	}


	public void setNombreusr_mod(String nombreusr_mod) {
		this.nombreusr_mod = nombreusr_mod;
	}

	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPOMODALIDADPAGO")
	public Tipomodalidadpago getTipomodalidadpago() {
		return tipomodalidadpago;
	}

	
	public void setTipomodalidadpago(Tipomodalidadpago tipomodalidadpago) {
		this.tipomodalidadpago = tipomodalidadpago;
	}

	@Column(name="TEXTOIMPORTETOTAL")
	public String getTextoimportetotal() {
		return textoimportetotal;
	}


	public void setTextoimportetotal(String textoimportetotal) {
		this.textoimportetotal = textoimportetotal;
	}

	@Column(name="COMP_DESCRIPCIONITEM")
	public String getComp_descripcionitem() {
		return comp_descripcionitem;
	}


	public void setComp_descripcionitem(String comp_descripcionitem) {
		this.comp_descripcionitem = comp_descripcionitem;
	}

	@Column(name="SIDOCUMENTO")
	public Boolean getSidocumento() {
		return sidocumento;
	}


	public void setSidocumento(Boolean sidocumento) {
		this.sidocumento = sidocumento;
	}

    @Column(name="TIPODOC_RECEPTOR")
	public String getTipodoc_receptor() {
		return tipodoc_receptor;
	}


	public void setTipodoc_receptor(String tipodoc_receptor) {
		this.tipodoc_receptor = tipodoc_receptor;
	}

//	@Column(name="MAC_OPERACION")
//	public String getMac_operacion() {
//		return mac_operacion;
//	}
//
//
//	public void setMac_operacion(String mac_operacion) {
//		this.mac_operacion = mac_operacion;
//	}
    
	
	
	
	
}


