package pe.gob.sblm.sgi.entity;
// Generated 25/08/2014 09:36:23 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contrato generated by hbm2java
 */
@Entity
@Table(name="CONTRATO"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class Contrato  implements java.io.Serializable {

     /**
	 * 
	 */
	 private static final long serialVersionUID = 1L;
	
	 private int idcontrato;
     private Inquilino inquilino;
     private Representante representante;
     private Representante representanteaval;
     private Institucion institucion;
     private Upa upa;
     private Cuentabancaria cuentabancaria;
     private Cliente cliente;
     private String tipo;
     private String tipocontrato;
     private Double montosolesgarantia;
     private Date iniciocontrato;
     private Date fincontrato;
     private String nrocontrato;
     private String aniocontrato;
     private String usoespecifico;
     private Integer numerocuotas;
     private Double montocuotasoles;
     private String tipomoneda;
     private Boolean siocupante;
     private String sinombreocupante;
     private String sidniocupante;
     
     private String factrenovacion;
    
     private Boolean sisuscrito;
     private Date sifechasuscrito;
    
     private String estado;
     private String resolucioninstitucion;
     private Date fechacreacion;
     private Date fechamodificacion;
     private String usuariocreador;
     private String usuariomodificador;
     private String aval;
     private String tipoaval;
     private String telefonoaval;
     private String motivorechazo;
     private Double factorincrementoanual;
     private Boolean sipenalidad;
     private Boolean de1a99;
     private Boolean de100a999;
     private Boolean de1000a9999;
     private Boolean de10000a48000;
     private Boolean de1a40;
     private Boolean de41a400;
     private Boolean de401a4000;
     private Boolean de4001a40000;

     private Integer nroperiodos;
     private Integer nroperiodoactual;
     private Double montocuotasoles2;
     private Double montocuotasoles3;
     private Double montocuotasoles4;
     private Double montocuotasoles5;
     private Double montocuotasoles6;
     private String numeroresolucion;

     private Boolean sicompromisopago;
     private Date fechacompromisopago;
     private String condicion;
     private Boolean sigarantia;
     private Double montodeuda;
     
     private String observacion;
     
     
     private Boolean siactaentrega;
     private Date sifechaactaentrega;
     private String numeroactaentrega;
     
     private Boolean siactadevolucion;
     private Date fechaactadevolucion;
     private String numeroactadevolucion;

     
     private Boolean sigeneroletra;
     private Date fechagiro;
     private Date fechavencimiento;
     
     
     private Date iniciocobro;
     private Date fincobro;
     private Date ultimafechapago;
     
     
     
     private Boolean sifinalizado; /**Finalizado natural*/
     private String observacionfinalizado;
     private Date fecmodfinalizado;
     
     private Boolean siverificado;
     
     
     private Boolean siresuelto;
     private String observacionresuelto;
     private Date fincontratoresuelto;
     private Date fecmodresuelto;
     
     private Boolean siadenda;
     private String observacionadenda;
     private Date fincontratoadenda;
     
     
     private Boolean siresolucion;
     private String observacionresolucion;
     private String nroresolucion;
     private Date fecharesolucion;
     private Date fecmodresolucion;
     
     private Boolean sicuotascanceladas;
     
     private Boolean sicartafianza;
     private Date fechavencimientocartafianza;
     private Double valorcartafianza;
     
     
     private Boolean siclausulareconocimientorenta;
     private Boolean siclausulaperiodogracia;
     private Boolean siclausulareconocimientoinversion;
     private Boolean siclausulapagoposterior;
     private Boolean sipagofraccionrenta;
     private Boolean siclausulasuspensiontemporalrenta;
     
     private Boolean sicontraprestacionadicional;
     
     private Double contraprestacionadicional;
     
     private String tiporeajusteanual;
     
     private Double reajusteanual;
     
     
     private Boolean sigeneracionrentacompletada;
     private Boolean sinuevomantenimiento;
     
     private Double porcentajepenalidad;
     private String observacionpenalidad;
     private Boolean sianulado;
     private String observacionanulado;
     private Boolean sidocumento;
     private Boolean sireconocimientodeuda;
     private Boolean simontoinicialdeuda;
     private Double montoinicialdeuda;
     private String nroacta;
     private Boolean siescriturapublica;
     private String ipoperacion;
     private Boolean sidetraccion;
     //Mantenimiento 
     private Boolean sireferenciareconocimientodeuda;
     private Integer idreconocimientodeuda;
     private String usr_cre_acta_recon_deuda;
     private Date fec_cre_acta_recon_deuda;
     private Date fec_inicio_acta;
     private Date fec_fin_acta;
     private Double monto_acta;
     private Double monto_inicial_acta;
     private Double monto_cuota_acta;
     private Integer nromeses_rec;
     private Date fec_inicio_rec;
     private Date fec_fin_rec;
     private String usr_anula;
     private Date fec_anula;
     private String motivo_anula;
     private String host_ip_cre;
     private String host_ip_mod;
     private String host_ip_anula;
     //incremento variable
     private Boolean siincrementovariable;
     private Boolean siincrementoporcentajevariable;
     private Boolean siincrementomontovariable;
     
     //
     private Fechapago fechapago;
     private Boolean siinteresmoratorio;
     private Boolean sicondicionclausula;
     
     private Set<MaeDetalleCondicion> maeDetalleCondicions = new HashSet<MaeDetalleCondicion>(0);
     
     private Set<PeriodoContrato> periodoContrato = new HashSet<PeriodoContrato>(0);
     
   
    public Contrato() {
    }

	
    public Contrato(int idcontrato) {
        this.idcontrato = idcontrato;
    }
   
   
     @Id 
     @GeneratedValue
    @Column(name="IDCONTRATO", unique=true, nullable=false)
    public int getIdcontrato() {
        return this.idcontrato;
    }
    
    public void setIdcontrato(int idcontrato) {
        this.idcontrato = idcontrato;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDINQUILINO")
    public Inquilino getInquilino() {
        return this.inquilino;
    }
    
    public void setInquilino(Inquilino inquilino) {
        this.inquilino = inquilino;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDREPRESENTANTEAVAL")
    public Representante getRepresentanteaval() {
        return this.representanteaval;
    }
    
    public void setRepresentanteaval(Representante representanteaval) {
        this.representanteaval = representanteaval;
    }
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDREPRESENTANTE")
	public Representante getRepresentante() {
		return this.representante;
	}

	public void setRepresentante(Representante representante) {
		this.representante = representante;
	}

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDINSTITUCION")
    public Institucion getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(Institucion institucion) {
        this.institucion = institucion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDUPA")
    public Upa getUpa() {
        return this.upa;
    }
    
    public void setUpa(Upa upa) {
        this.upa = upa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCUENTABANCARIA")
    public Cuentabancaria getCuentabancaria() {
        return this.cuentabancaria;
    }
    
    public void setCuentabancaria(Cuentabancaria cuentabancaria) {
        this.cuentabancaria = cuentabancaria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCLIENTE")
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="TIPO", length=20)
    public String getTipo() {
        return this.tipo;
    }
 

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="TIPOCONTRATO", length=20)  
    public String getTipocontrato() {
		return this.tipocontrato;
	}


	public void setTipocontrato(String tipocontrato) {
		this.tipocontrato = tipocontrato;
	}


	@Column(name="MONTOSOLESGARANTIA", precision=53, scale=0)
    public Double getMontosolesgarantia() {
        return this.montosolesgarantia;
    }
    
    public void setMontosolesgarantia(Double montosolesgarantia) {
        this.montosolesgarantia = montosolesgarantia;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INICIOCONTRATO", length=23)
    public Date getIniciocontrato() {
        return this.iniciocontrato;
    }
    
    public void setIniciocontrato(Date iniciocontrato) {
        this.iniciocontrato = iniciocontrato;
    }
    


	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FINCONTRATO", length=23)
    public Date getFincontrato() {
        return this.fincontrato;
    }
    
    
	@Temporal(TemporalType.DATE)
    @Column(name="INICIOCOBRO", length=10)  
    public Date getIniciocobro() {
		return iniciocobro;
	}


	public void setIniciocobro(Date iniciocobro) {
		this.iniciocobro = iniciocobro;
	}

	@Temporal(TemporalType.DATE)
    @Column(name="FINCOBRO", length=10)
	public Date getFincobro() {
		return fincobro;
	}


	public void setFincobro(Date fincobro) {
		this.fincobro = fincobro;
	}


	public void setFincontrato(Date fincontrato) {
        this.fincontrato = fincontrato;
    }

    
    @Column(name="NROCONTRATO", length=15)
    public String getNrocontrato() {
        return this.nrocontrato;
    }
    
    public void setNrocontrato(String nrocontrato) {
        this.nrocontrato = nrocontrato;
    }

    
    @Column(name="ANIOCONTRATO", length=15)
    public String getAniocontrato() {
        return this.aniocontrato;
    }
    
    public void setAniocontrato(String aniocontrato) {
        this.aniocontrato = aniocontrato;
    }

    
    @Column(name="USOESPECIFICO", length=100)
    public String getUsoespecifico() {
        return this.usoespecifico;
    }
    
    public void setUsoespecifico(String usoespecifico) {
        this.usoespecifico = usoespecifico;
    }

    
    @Column(name="NUMEROCUOTAS")
    public Integer getNumerocuotas() {
        return this.numerocuotas;
    }
    
    public void setNumerocuotas(Integer numerocuotas) {
        this.numerocuotas = numerocuotas;
    }
    
    @Column(name="MONTOCUOTASOLES", precision=53, scale=0)
    public Double getMontocuotasoles() {
        return this.montocuotasoles;
    }
    
    public void setMontocuotasoles(Double montocuotasoles) {
        this.montocuotasoles = montocuotasoles;
    }

    
    @Column(name="TIPOMONEDA", length=1)
    public String getTipomoneda() {
        return this.tipomoneda;
    }
    
    public void setTipomoneda(String tipomoneda) {
        this.tipomoneda = tipomoneda;
    }

    
    @Column(name="SIOCUPANTE")
    public Boolean getSiocupante() {
        return this.siocupante;
    }
    
    public void setSiocupante(Boolean siocupante) {
        this.siocupante = siocupante;
    }
    
    

    @Column(name="SIVERIFICADO")  
	public Boolean getSiverificado() {
		return siverificado;
	}


	public void setSiverificado(Boolean siverificado) {
		this.siverificado = siverificado;
	}


	@Column(name="SINOMBREOCUPANTE", length=50)
    public String getSinombreocupante() {
        return this.sinombreocupante;
    }
    
    public void setSinombreocupante(String sinombreocupante) {
        this.sinombreocupante = sinombreocupante;
    }

    
    @Column(name="FACTRENOVACION", length=100)
    public String getFactrenovacion() {
        return this.factrenovacion;
    }
    
    public void setFactrenovacion(String factrenovacion) {
        this.factrenovacion = factrenovacion;
    }

    
    @Column(name="SISUSCRITO")
    public Boolean getSisuscrito() {
        return this.sisuscrito;
    }
    
    public void setSisuscrito(Boolean sisuscrito) {
        this.sisuscrito = sisuscrito;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SIFECHASUSCRITO", length=23)
    public Date getSifechasuscrito() {
        return this.sifechasuscrito;
    }
    
    public void setSifechasuscrito(Date sifechasuscrito) {
        this.sifechasuscrito = sifechasuscrito;
    }

    
    @Column(name="SIACTAENTREGA")
    public Boolean getSiactaentrega() {
        return this.siactaentrega;
    }
    
    public void setSiactaentrega(Boolean siactaentrega) {
        this.siactaentrega = siactaentrega;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SIFECHAACTAENTREGA", length=23)
    public Date getSifechaactaentrega() {
        return this.sifechaactaentrega;
    }
    
    public void setSifechaactaentrega(Date sifechaactaentrega) {
        this.sifechaactaentrega = sifechaactaentrega;
    }

    
    @Column(name="ESTADO", length=10)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Column(name="OBSERVACIONRESUELTO", length=200)  
	public String getObservacionresuelto() {
		return observacionresuelto;
	}


	public void setObservacionresuelto(String observacionresuelto) {
		this.observacionresuelto = observacionresuelto;
	}
	
	
    @Column(name="OBSERVACIONADENDA", length=200)  
	public String getObservacionadenda() {
		return observacionadenda;
	}


	public void setObservacionadenda(String observacionadenda) {
		this.observacionadenda = observacionadenda;
	}


	@Column(name="RESOLUCIONINSTITUCION", length=100)
    public String getResolucioninstitucion() {
        return this.resolucioninstitucion;
    }
    
    public void setResolucioninstitucion(String resolucioninstitucion) {
        this.resolucioninstitucion = resolucioninstitucion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHACREACION", length=23)
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAMODIFICACION", length=23)
    public Date getFechamodificacion() {
        return this.fechamodificacion;
    }
    
    public void setFechamodificacion(Date fechamodificacion) {
        this.fechamodificacion = fechamodificacion;
    }

    
    @Column(name="USUARIOCREADOR", length=100)
    public String getUsuariocreador() {
        return this.usuariocreador;
    }
    
    public void setUsuariocreador(String usuariocreador) {
        this.usuariocreador = usuariocreador;
    }

    
    @Column(name="USUARIOMODIFICADOR", length=100)
    public String getUsuariomodificador() {
        return this.usuariomodificador;
    }
    
    public void setUsuariomodificador(String usuariomodificador) {
        this.usuariomodificador = usuariomodificador;
    }

    
    @Column(name="AVAL", length=100)
    public String getAval() {
        return this.aval;
    }
    
    public void setAval(String aval) {
        this.aval = aval;
    }

    
    @Column(name="TIPOAVAL", length=50)
    public String getTipoaval() {
        return this.tipoaval;
    }
    
    public void setTipoaval(String tipoaval) {
        this.tipoaval = tipoaval;
    }

    
    @Column(name="TELEFONOAVAL", length=20)
    public String getTelefonoaval() {
        return this.telefonoaval;
    }
    
    public void setTelefonoaval(String telefonoaval) {
        this.telefonoaval = telefonoaval;
    }

    
    @Column(name="MOTIVORECHAZO", length=200)
    public String getMotivorechazo() {
        return this.motivorechazo;
    }
    
    public void setMotivorechazo(String motivorechazo) {
        this.motivorechazo = motivorechazo;
    }

    
    @Column(name="FACTORINCREMENTOANUAL", precision=53, scale=0)
    public Double getFactorincrementoanual() {
        return this.factorincrementoanual;
    }
    
    public void setFactorincrementoanual(Double factorincrementoanual) {
        this.factorincrementoanual = factorincrementoanual;
    }

    
    @Column(name="SIPENALIDAD")
    public Boolean getSipenalidad() {
        return this.sipenalidad;
    }
    
    public void setSipenalidad(Boolean sipenalidad) {
        this.sipenalidad = sipenalidad;
    }

    
    @Column(name="DE1A99")
    public Boolean getDe1a99() {
        return this.de1a99;
    }
    
    public void setDe1a99(Boolean de1a99) {
        this.de1a99 = de1a99;
    }

    
    @Column(name="DE100A999")
    public Boolean getDe100a999() {
        return this.de100a999;
    }
    
    public void setDe100a999(Boolean de100a999) {
        this.de100a999 = de100a999;
    }

    
    @Column(name="DE1000A9999")
    public Boolean getDe1000a9999() {
        return this.de1000a9999;
    }
    
    public void setDe1000a9999(Boolean de1000a9999) {
        this.de1000a9999 = de1000a9999;
    }

    
    @Column(name="DE10000A48000")
    public Boolean getDe10000a48000() {
        return this.de10000a48000;
    }
    
    public void setDe10000a48000(Boolean de10000a48000) {
        this.de10000a48000 = de10000a48000;
    }

    
    @Column(name="DE1A40")
    public Boolean getDe1a40() {
        return this.de1a40;
    }
    
    public void setDe1a40(Boolean de1a40) {
        this.de1a40 = de1a40;
    }

    
    @Column(name="DE41A400")
    public Boolean getDe41a400() {
        return this.de41a400;
    }
    
    public void setDe41a400(Boolean de41a400) {
        this.de41a400 = de41a400;
    }

    
    @Column(name="DE401A4000")
    public Boolean getDe401a4000() {
        return this.de401a4000;
    }
    
    public void setDe401a4000(Boolean de401a4000) {
        this.de401a4000 = de401a4000;
    }

    
    @Column(name="DE4001A40000")
    public Boolean getDe4001a40000() {
        return this.de4001a40000;
    }
    
    public void setDe4001a40000(Boolean de4001a40000) {
        this.de4001a40000 = de4001a40000;
    }

    
    @Column(name="SIRESUELTO")
    public Boolean getSiresuelto() {
		return siresuelto;
	}


	public void setSiresuelto(Boolean siresuelto) {
		this.siresuelto = siresuelto;
	}




    
    @Column(name="NROPERIODOS")
    public Integer getNroperiodos() {
        return this.nroperiodos;
    }
    

	public Date getFecmodresuelto() {
		return fecmodresuelto;
	}

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECMODRESUELTO", length=23)
	public void setFecmodresuelto(Date fecmodresuelto) {
		this.fecmodresuelto = fecmodresuelto;
	}


	public void setNroperiodos(Integer nroperiodos) {
        this.nroperiodos = nroperiodos;
    }

    
    @Column(name="NROPERIODOACTUAL")
    public Integer getNroperiodoactual() {
        return this.nroperiodoactual;
    }
    
    public void setNroperiodoactual(Integer nroperiodoactual) {
        this.nroperiodoactual = nroperiodoactual;
    }

    
    @Column(name="MONTOCUOTASOLES2", precision=53, scale=0)
    public Double getMontocuotasoles2() {
        return this.montocuotasoles2;
    }
    
    public void setMontocuotasoles2(Double montocuotasoles2) {
        this.montocuotasoles2 = montocuotasoles2;
    }

    
    @Column(name="MONTOCUOTASOLES3", precision=53, scale=0)
    public Double getMontocuotasoles3() {
        return this.montocuotasoles3;
    }
    
    public void setMontocuotasoles3(Double montocuotasoles3) {
        this.montocuotasoles3 = montocuotasoles3;
    }

    
    @Column(name="MONTOCUOTASOLES4", precision=53, scale=0)
    public Double getMontocuotasoles4() {
        return this.montocuotasoles4;
    }
    
    public void setMontocuotasoles4(Double montocuotasoles4) {
        this.montocuotasoles4 = montocuotasoles4;
    }

    
    @Column(name="MONTOCUOTASOLES5", precision=53, scale=0)
    public Double getMontocuotasoles5() {
        return this.montocuotasoles5;
    }
    
    public void setMontocuotasoles5(Double montocuotasoles5) {
        this.montocuotasoles5 = montocuotasoles5;
    }

    
    @Column(name="MONTOCUOTASOLES6", precision=53, scale=0)
    public Double getMontocuotasoles6() {
        return this.montocuotasoles6;
    }
    
    public void setMontocuotasoles6(Double montocuotasoles6) {
        this.montocuotasoles6 = montocuotasoles6;
    }

    
    @Column(name="NUMERORESOLUCION", length=100)
    public String getNumeroresolucion() {
        return this.numeroresolucion;
    }
    
    public void setNumeroresolucion(String numeroresolucion) {
        this.numeroresolucion = numeroresolucion;
    }

    
    @Column(name="NUMEROACTAENTREGA", length=100)
    public String getNumeroactaentrega() {
        return this.numeroactaentrega;
    }
    
    public void setNumeroactaentrega(String numeroactaentrega) {
        this.numeroactaentrega = numeroactaentrega;
    }
    
    @Column(name="SIACTADEVOLUCION")
	public Boolean getSiactadevolucion() {
		return siactadevolucion;
	}


	public void setSiactadevolucion(Boolean siactadevolucion) {
		this.siactadevolucion = siactadevolucion;
	}

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAACTADEVOLUCION", length=23)
	public Date getFechaactadevolucion() {
		return fechaactadevolucion;
	}


	public void setFechaactadevolucion(Date fechaactadevolucion) {
		this.fechaactadevolucion = fechaactadevolucion;
	}

    @Column(name="NUMEROACTADEVOLUCION", length=100)
	public String getNumeroactadevolucion() {
		return numeroactadevolucion;
	}


	public void setNumeroactadevolucion(String numeroactadevolucion) {
		this.numeroactadevolucion = numeroactadevolucion;
	}

    
    @Column(name="OBSERVACION", length=500)   
    public String getObservacion() {
		return observacion;
	}


	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}


	@Column(name="SICOMPROMISOPAGO")
    public Boolean getSicompromisopago() {
        return this.sicompromisopago;
    }
    
    public void setSicompromisopago(Boolean sicompromisopago) {
        this.sicompromisopago = sicompromisopago;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHACOMPROMISOPAGO", length=23)
    public Date getFechacompromisopago() {
        return this.fechacompromisopago;
    }
    
    public void setFechacompromisopago(Date fechacompromisopago) {
        this.fechacompromisopago = fechacompromisopago;
    }

    
    @Column(name="CONDICION", length=12)
    public String getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }

    
    @Column(name="SIGARANTIA")
    public Boolean getSigarantia() {
        return this.sigarantia;
    }
    
    public void setSigarantia(Boolean sigarantia) {
        this.sigarantia = sigarantia;
    }

    
    @Column(name="MONTODEUDA", precision=53, scale=0)
    public Double getMontodeuda() {
        return this.montodeuda;
    }
    
    public void setMontodeuda(Double montodeuda) {
        this.montodeuda = montodeuda;
    }
    @Column(name="SIDNIOCUPANTE", length=10)
    public String getSidniocupante() {
        return this.sidniocupante;
    }
    
    public void setSidniocupante(String sidniocupante) {
        this.sidniocupante = sidniocupante;
    }

    
    @Column(name="SIGENEROLETRA")
    public Boolean getSigeneroletra() {
        return this.sigeneroletra;
    }
    
    public void setSigeneroletra(Boolean sigeneroletra) {
        this.sigeneroletra = sigeneroletra;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAGIRO", length=23)
    public Date getFechagiro() {
        return this.fechagiro;
    }
    
    public void setFechagiro(Date fechagiro) {
        this.fechagiro = fechagiro;
    }
    
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FINCONTRATORESUELTO", length=23)
    public Date getFincontratoresuelto() {
		return fincontratoresuelto;
	}


	public void setFincontratoresuelto(Date fincontratoresuelto) {
		this.fincontratoresuelto = fincontratoresuelto;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAVENCIMIENTO", length=23)
    public Date getFechavencimiento() {
        return this.fechavencimiento;
    }
    



	public void setFechavencimiento(Date fechavencimiento) {
        this.fechavencimiento = fechavencimiento;
    }

	public Boolean getSicuotascanceladas() {
		return sicuotascanceladas;
	}


	public void setSicuotascanceladas(Boolean sicuotascanceladas) {
		this.sicuotascanceladas = sicuotascanceladas;
	}



    @Temporal(TemporalType.DATE)
    @Column(name="ULTIMAFECHAPAGO", length=23)    
	public Date getUltimafechapago() {
		return ultimafechapago;
	}


	public void setUltimafechapago(Date ultimafechapago) {
		this.ultimafechapago = ultimafechapago;
	}

    @Column(name="SIFINALIZADO")
	public Boolean getSifinalizado() {
		return sifinalizado;
	}


	public void setSifinalizado(Boolean sifinalizado) {
		this.sifinalizado = sifinalizado;
	}

    @Column(name="SIADENDA")
	public Boolean getSiadenda() {
		return siadenda;
	}

	public void setSiadenda(Boolean siadenda) {
		this.siadenda = siadenda;
	}

    @Column(name="OBSERVACIONFINALIZADO", length=200)
	public String getObservacionfinalizado() {
		return observacionfinalizado;
	}


	public void setObservacionfinalizado(String observacionfinalizado) {
		this.observacionfinalizado = observacionfinalizado;
	}

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECMODFINALIZADO", length=23)
	public Date getFecmodfinalizado() {
		return fecmodfinalizado;
	}

	public void setFecmodfinalizado(Date fecmodfinalizado) {
		this.fecmodfinalizado = fecmodfinalizado;
	}
	
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FINCONTRATOADENDA", length=23)
	public Date getFincontratoadenda() {
		return fincontratoadenda;
	}
	public void setFincontratoadenda(Date fincontratoadenda) {
		this.fincontratoadenda = fincontratoadenda;
	}

    @Column(name="SIRESOLUCION")
	public Boolean getSiresolucion() {
		return siresolucion;
	}


	public void setSiresolucion(Boolean siresolucion) {
		this.siresolucion = siresolucion;
	}

    @Column(name="OBSERVACIONRESOLUCION", length=200)
	public String getObservacionresolucion() {
		return observacionresolucion;
	}


	public void setObservacionresolucion(String observacionresolucion) {
		this.observacionresolucion = observacionresolucion;
	}

    @Column(name="NRORESOLUCION", length=50)
	public String getNroresolucion() {
		return nroresolucion;
	}


	public void setNroresolucion(String nroresolucion) {
		this.nroresolucion = nroresolucion;
	}

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHARESOLUCION", length=23)
	public Date getFecharesolucion() {
		return fecharesolucion;
	}


	public void setFecharesolucion(Date fecharesolucion) {
		this.fecharesolucion = fecharesolucion;
	}

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECMODRESOLUCION", length=23)
	public Date getFecmodresolucion() {
		return fecmodresolucion;
	}


	public void setFecmodresolucion(Date fecmodresolucion) {
		this.fecmodresolucion = fecmodresolucion;
	}

    @Column(name="SICARTAFIANZA")
	public Boolean getSicartafianza() {
		return sicartafianza;
	}


	public void setSicartafianza(Boolean sicartafianza) {
		this.sicartafianza = sicartafianza;
	}

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAVENCIMIENTOCARTAFIANZA", length=23)
	public Date getFechavencimientocartafianza() {
		return fechavencimientocartafianza;
	}


	public void setFechavencimientocartafianza(Date fechavencimientocartafianza) {
		this.fechavencimientocartafianza = fechavencimientocartafianza;
	}


    @Column(name="VALORCARTAFIANZA")
	public Double getValorcartafianza() {
		return valorcartafianza;
	}

	public void setValorcartafianza(Double valorcartafianza) {
		this.valorcartafianza = valorcartafianza;
	}

    @Column(name="SICLAUSULARECONOCIMIENTORENTA")
	public Boolean getSiclausulareconocimientorenta() {
		return siclausulareconocimientorenta;
    }


	public void setSiclausulareconocimientorenta(
			Boolean siclausulareconocimientorenta) {
		this.siclausulareconocimientorenta = siclausulareconocimientorenta;
	}

    @Column(name="SICLAUSULAPERIODOGRACIA")
	public Boolean getSiclausulaperiodogracia() {
		return siclausulaperiodogracia;
	}


	public void setSiclausulaperiodogracia(Boolean siclausulaperiodogracia) {
		this.siclausulaperiodogracia = siclausulaperiodogracia;
	}

    @Column(name="SICLAUSULARECONOCIMIENTOINVERSION")
	public Boolean getSiclausulareconocimientoinversion() {
		return siclausulareconocimientoinversion;
	}


	public void setSiclausulareconocimientoinversion(
			Boolean siclausulareconocimientoinversion) {
		this.siclausulareconocimientoinversion = siclausulareconocimientoinversion;
	}

    @Column(name="SICLAUSULAPAGOPOSTERIOR")
	public Boolean getSiclausulapagoposterior() {
		return siclausulapagoposterior;
	}


	public void setSiclausulapagoposterior(Boolean siclausulapagoposterior) {
		this.siclausulapagoposterior = siclausulapagoposterior;
	}

	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="contrato")
	public Set<MaeDetalleCondicion> getMaeDetalleCondicions() {
		return maeDetalleCondicions;
	}


	public void setMaeDetalleCondicions(
			Set<MaeDetalleCondicion> maeDetalleCondicions) {
		this.maeDetalleCondicions = maeDetalleCondicions;
	}
    
	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="contrato")
	public Set<PeriodoContrato> getPeriodoContrato() {
		return periodoContrato;
	}


	public void setPeriodoContrato(
			Set<PeriodoContrato> periodoContrato) {
		this.periodoContrato = periodoContrato;
	}
	
    @Column(name="SIPAGOFRACCIONRENTA")
	public Boolean getSipagofraccionrenta() {
		return sipagofraccionrenta;
	}


	public void setSipagofraccionrenta(Boolean sipagofraccionrenta) {
		this.sipagofraccionrenta = sipagofraccionrenta;
	}
	
	
    @Column(name="SICLAUSULASUSPENSIONTEMPORALRENTA")
    public Boolean getSiclausulasuspensiontemporalrenta() {
		return siclausulasuspensiontemporalrenta;
	}


	public void setSiclausulasuspensiontemporalrenta(Boolean siclausulasuspensiontemporalrenta) {
		this.siclausulasuspensiontemporalrenta = siclausulasuspensiontemporalrenta;
	}


	@Column(name="SICONTRAPRESTACIONADICIONAL")
	public Boolean getSicontraprestacionadicional() {
		return sicontraprestacionadicional;
	}


	public void setSicontraprestacionadicional(Boolean sicontraprestacionadicional) {
		this.sicontraprestacionadicional = sicontraprestacionadicional;
	}


    @Column(name="CONTRAPRESTACIONADICIONAL", precision=53, scale=0)
	public Double getContraprestacionadicional() {
		return contraprestacionadicional;
	}


	public void setContraprestacionadicional(Double contraprestacionadicional) {
		this.contraprestacionadicional = contraprestacionadicional;
	}

    @Column(name="TIPOREAJUSTEANUAL", length=1)
	public String getTiporeajusteanual() {
		return tiporeajusteanual;
	}


	public void setTiporeajusteanual(String tiporeajusteanual) {
		this.tiporeajusteanual = tiporeajusteanual;
	}

    @Column(name="REAJUSTEANUAL", precision=53, scale=0)
	public Double getReajusteanual() {
		return reajusteanual;
	}


	public void setReajusteanual(Double reajusteanual) {
		this.reajusteanual = reajusteanual;
	}

    @Column(name="SIGENERACIONRENTACOMPLETADA")
	public Boolean getSigeneracionrentacompletada() {
		return sigeneracionrentacompletada;
	}


	public void setSigeneracionrentacompletada(Boolean sigeneracionrentacompletada) {
		this.sigeneracionrentacompletada = sigeneracionrentacompletada;
	}

    @Column(name="SINUEVOMANTENIMIENTO")
	public Boolean getSinuevomantenimiento() {
		return sinuevomantenimiento;
	}


	public void setSinuevomantenimiento(Boolean sinuevomantenimiento) {
		this.sinuevomantenimiento = sinuevomantenimiento;
    }


    @Column(name="PORCENTAJEPENALIDAD", precision=53, scale=0)
	public Double getPorcentajepenalidad() {
		return porcentajepenalidad;
	}


	public void setPorcentajepenalidad(Double porcentajepenalidad) {
		this.porcentajepenalidad = porcentajepenalidad;
	}

    @Column(name="OBSERVACIONPENALIDAD", length=200)
	public String getObservacionpenalidad() {
		return observacionpenalidad;
	}


	public void setObservacionpenalidad(String observacionpenalidad) {
		this.observacionpenalidad = observacionpenalidad;
	}

	@Column(name="SIANULADO", length=1)
	public Boolean getSianulado() {
		return sianulado;
	}

	public void setSianulado(Boolean sianulado) {
		this.sianulado = sianulado;
	}

	@Column(name="OBSERVACIONANULADO", length=200)
	public String getObservacionanulado() {
		return observacionanulado;
	}


	public void setObservacionanulado(String observacionanulado) {
		this.observacionanulado = observacionanulado;
	}

	@Column(name="SIDOCUMENTO")
	public Boolean getSidocumento() {
		return sidocumento;
	}


	public void setSidocumento(Boolean sidocumento) {
		this.sidocumento = sidocumento;
	}

    @Column(name="SIRECONOCIMIENTODEUDA")
	public Boolean getSireconocimientodeuda() {
		return sireconocimientodeuda;
	}


	public void setSireconocimientodeuda(Boolean sireconocimientodeuda) {
		this.sireconocimientodeuda = sireconocimientodeuda;
	}

    @Column(name="SIMONTOINICIALDEUDA")
	public Boolean getSimontoinicialdeuda() {
		return simontoinicialdeuda;
	}


	public void setSimontoinicialdeuda(Boolean simontoinicialdeuda) {
		this.simontoinicialdeuda = simontoinicialdeuda;
	}

    @Column(name="MONTOINICIALDEUDA", precision=53, scale=0)
	public Double getMontoinicialdeuda() {
		return montoinicialdeuda;
	}


	public void setMontoinicialdeuda(Double montoinicialdeuda) {
		this.montoinicialdeuda = montoinicialdeuda;
	}

	@Column(name="NROACTA", length=15)
	public String getNroacta() {
		return nroacta;
	}


	public void setNroacta(String nroacta) {
		this.nroacta = nroacta;
	}

	@Column(name="SIESCRITURAPUBLICA")
	public Boolean getSiescriturapublica() {
		return siescriturapublica;
	}


	public void setSiescriturapublica(Boolean siescriturapublica) {
		this.siescriturapublica = siescriturapublica;
	}

	@Column(name="IP_OPERACION")
	public String getIpoperacion() {
		return ipoperacion;
	}


	public void setIpoperacion(String ipoperacion) {
		this.ipoperacion = ipoperacion;
	}

	@Column(name="SIDETRACCION")
	public Boolean getSidetraccion() {
		return sidetraccion;
	}


	public void setSidetraccion(Boolean sidetraccion) {
		this.sidetraccion = sidetraccion;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_INICIO_ACTA", length=23)
	public Date getFec_inicio_acta() {
		return fec_inicio_acta;
	}


	public void setFec_inicio_acta(Date fec_inicio_acta) {
		this.fec_inicio_acta = fec_inicio_acta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="FEC_FIN_ACTA" ,length=23)
	public Date getFec_fin_acta() {
		return fec_fin_acta;
	}


	public void setFec_fin_acta(Date fec_fin_acta) {
		this.fec_fin_acta = fec_fin_acta;
	}

    @Column(name="MONTO_ACTA")
	public Double getMonto_acta() {
		return monto_acta;
	}


	public void setMonto_acta(Double monto_acta) {
		this.monto_acta = monto_acta;
	}

	@Column(name="MONTO_INICIAL_ACTA")
	public Double getMonto_inicial_acta() {
		return monto_inicial_acta;
	}


	public void setMonto_inicial_acta(Double monto_inicial_acta) {
		this.monto_inicial_acta = monto_inicial_acta;
	}

    @Column(name="MONTO_CUOTA_ACTA")
	public Double getMonto_cuota_acta() {
		return monto_cuota_acta;
	}


	public void setMonto_cuota_acta(Double monto_cuota_acta) {
		this.monto_cuota_acta = monto_cuota_acta;
	}

    @Column(name="NROMESES_REC")
	public Integer getNromeses_rec() {
		return nromeses_rec;
	}


	public void setNromeses_rec(Integer nromeses_rec) {
		this.nromeses_rec = nromeses_rec;
	}
    
	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_INICIO_REC" ,length=23)
	public Date getFec_inicio_rec() {
		return fec_inicio_rec;
	}


	public void setFec_inicio_rec(Date fec_inicio_rec) {
		this.fec_inicio_rec = fec_inicio_rec;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="FEC_FIN_REC" ,length=23)
	public Date getFec_fin_rec() {
		return fec_fin_rec;
	}


	public void setFec_fin_rec(Date fec_fin_rec) {
		this.fec_fin_rec = fec_fin_rec;
	}

    @Column(name="USR_ANULA")
	public String getUsr_anula() {
		return usr_anula;
	}


	public void setUsr_anula(String usr_anula) {
		this.usr_anula = usr_anula;
	}

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_ANULA",length=23)
	public Date getFec_anula() {
		return fec_anula;
	}


	public void setFec_anula(Date fec_anula) {
		this.fec_anula = fec_anula;
	}

    @Column(name="MOTIVO_ANULA" , length=1000)
	public String getMotivo_anula() {
		return motivo_anula;
	}


	public void setMotivo_anula(String motivo_anula) {
		this.motivo_anula = motivo_anula;
	}

    @Column(name="HOST_IP_CRE" , length=100)
	public String getHost_ip_cre() {
		return host_ip_cre;
	}


	public void setHost_ip_cre(String host_ip_cre) {
		this.host_ip_cre = host_ip_cre;
	}

    @Column(name="HOST_IP_MOD" , length=100)
	public String getHost_ip_mod() {
		return host_ip_mod;
	}


	public void setHost_ip_mod(String host_ip_mod) {
		this.host_ip_mod = host_ip_mod;
	}

    @Column(name="HOST_IP_ANULA" , length=100)
	public String getHost_ip_anula() {
		return host_ip_anula;
	}


	public void setHost_ip_anula(String host_ip_anula) {
		this.host_ip_anula = host_ip_anula;
	}

	 @Column(name="SIREFERENCIARECONOCIMIENTODEUDA")
	public Boolean getSireferenciareconocimientodeuda() {
		return sireferenciareconocimientodeuda;
	}


	public void setSireferenciareconocimientodeuda(
			Boolean sireferenciareconocimientodeuda) {
		this.sireferenciareconocimientodeuda = sireferenciareconocimientodeuda;
	}

	 @Column(name="IDRECONOCIMIENTODEUDA")
	public Integer getIdreconocimientodeuda() {
		return idreconocimientodeuda;
	}


	public void setIdreconocimientodeuda(Integer idreconocimientodeuda) {
		this.idreconocimientodeuda = idreconocimientodeuda;
	}

	 @Column(name="USR_CRE_ACTA_RECON_DEUDA")
	public String getUsr_cre_acta_recon_deuda() {
		return usr_cre_acta_recon_deuda;
	}


	public void setUsr_cre_acta_recon_deuda(String usr_cre_acta_recon_deuda) {
		this.usr_cre_acta_recon_deuda = usr_cre_acta_recon_deuda;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_CRE_ACTA_RECON_DEUDA",length=23)
	public Date getFec_cre_acta_recon_deuda() {
		return fec_cre_acta_recon_deuda;
	}


	public void setFec_cre_acta_recon_deuda(Date fec_cre_acta_recon_deuda) {
		this.fec_cre_acta_recon_deuda = fec_cre_acta_recon_deuda;
	}

    @Column(name="SIINCREMENTOVARIABLE")
	public Boolean getSiincrementovariable() {
		return siincrementovariable;
	}


	public void setSiincrementovariable(Boolean siincrementovariable) {
		this.siincrementovariable = siincrementovariable;
	}

	@Column(name="SIINCREMENTOPORCENTAJEVARIABLE")
	public Boolean getSiincrementoporcentajevariable() {
		return siincrementoporcentajevariable;
	}


	public void setSiincrementoporcentajevariable(
			Boolean siincrementoporcentajevariable) {
		this.siincrementoporcentajevariable = siincrementoporcentajevariable;
	}

	@Column(name="SIINCREMENTOMONTOVARIABLE")
	public Boolean getSiincrementomontovariable() {
		return siincrementomontovariable;
	}


	public void setSiincrementomontovariable(Boolean siincrementomontovariable) {
		this.siincrementomontovariable = siincrementomontovariable;
	}

	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDFECHAPAGO")
	public Fechapago getFechapago() {
		return fechapago;
	}


	public void setFechapago(Fechapago fechapago) {
		this.fechapago = fechapago;
	}

    @Column(name="SIINTERESMORATORIO")
	public Boolean getSiinteresmoratorio() {
		return siinteresmoratorio;
	}


	public void setSiinteresmoratorio(Boolean siinteresmoratorios) {
		this.siinteresmoratorio = siinteresmoratorios;
	}

	@Column(name="SICONDICIONCLAUSULA")
	public Boolean getSicondicionclausula() {
		return sicondicionclausula;
	}


	public void setSicondicionclausula(Boolean sicondicionclausula) {
		this.sicondicionclausula = sicondicionclausula;
	}
   
	

	
}