package pe.gob.sblm.sgi.entity;
// Generated 25/08/2014 09:36:23 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cuota generated by hbm2java
 */
@Entity
@Table(name="CUOTA"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class Cuota  implements java.io.Serializable {


     private int idcuota;
     private Contrato contrato;
     private Double montosoles;
     private Double morasoles;
     private String usrcre;
     private String usrmod;
     private Date feccre;
     private Date fecmod;
     private String cancelado;
     private String cuotanumero;
     private Integer nropagos;
     private Integer aniocuotames;
     private String mespagado;
     private Double tipocambio;
     private Integer nromes;
     private MaeDetalleCondicion maeDetalleCondicion;
     private Set<Detallecuota> detallecuotas = new HashSet<Detallecuota>(0);
     private Comprobantepago comprobantepago;
     private String estado;
     private String observacion;
     private Double montopenalizacion;
    public Cuota() {
    }

   
     @Id 
     @GeneratedValue
    @Column(name="IDCUOTA", unique=true, nullable=false)
    public int getIdcuota() {
        return this.idcuota;
    }
    
    public void setIdcuota(int idcuota) {
        this.idcuota = idcuota;
    }

	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCONTRATO")
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_DETALLE_CONDICION")
    public MaeDetalleCondicion getMaeDetalleCondicion() {
		return maeDetalleCondicion;
	}


	public void setMaeDetalleCondicion(MaeDetalleCondicion maeDetalleCondicion) {
		this.maeDetalleCondicion = maeDetalleCondicion;
	}

    
    @Column(name="MONTOSOLES", precision=53, scale=0)
    public Double getMontosoles() {
        return this.montosoles;
    }
    

    public void setMontosoles(Double montosoles) {
        this.montosoles = montosoles;
    }

    
    @Column(name="MORASOLES", precision=53, scale=0)
    public Double getMorasoles() {
        return this.morasoles;
    }
    
    public void setMorasoles(Double morasoles) {
        this.morasoles = morasoles;
    }


    @Column(name="USRCRE", length=50)
    public String getUsrcre() {
        return this.usrcre;
    }
    
    public void setUsrcre(String usrcre) {
        this.usrcre = usrcre;
    }

    
    @Column(name="USRMOD", length=50)
    public String getUsrmod() {
        return this.usrmod;
    }
    
    public void setUsrmod(String usrmod) {
        this.usrmod = usrmod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECCRE", length=23)
    public Date getFeccre() {
        return this.feccre;
    }
    
    public void setFeccre(Date feccre) {
        this.feccre = feccre;
    }


	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECMOD", length=23)
    public Date getFecmod() {
        return this.fecmod;
    }
    
    public void setFecmod(Date fecmod) {
        this.fecmod = fecmod;
    }

    
    @Column(name="CANCELADO")
    public String getCancelado() {
		return cancelado;
	}


	public void setCancelado(String cancelado) {
		this.cancelado = cancelado;
	}

    
    @Column(name="CUOTANUMERO", length=12)
    public String getCuotanumero() {
        return this.cuotanumero;
    }
    



	public void setCuotanumero(String cuotanumero) {
        this.cuotanumero = cuotanumero;
    }

    
    @Column(name="NROPAGOS")
    public Integer getNropagos() {
        return this.nropagos;
    }
    
    public void setNropagos(Integer nropagos) {
        this.nropagos = nropagos;
    }
    
    
    @Column(name="NROMES")
    public Integer getNromes() {
		return nromes;
	}


	public void setNromes(Integer nromes) {
		this.nromes = nromes;
	}


	@Column(name="ANIOCUOTAMES")
    public Integer getAniocuotames() {
        return this.aniocuotames;
    }
    
    public void setAniocuotames(Integer aniocuotames) {
        this.aniocuotames = aniocuotames;
    }
    
    @Column(name="MESPAGADO", length=15)
    public String getMespagado() {
        return this.mespagado;
    }
    
    public void setMespagado(String mespagado) {
        this.mespagado = mespagado;
    }

    
    @Column(name="TIPOCAMBIO", precision=53, scale=0)
    public Double getTipocambio() {
        return this.tipocambio;
    }
    
    public void setTipocambio(Double tipocambio) {
        this.tipocambio = tipocambio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cuota")
    public Set<Detallecuota> getDetallecuotas() {
        return this.detallecuotas;
    }
    
    public void setDetallecuotas(Set<Detallecuota> detallecuotas) {
        this.detallecuotas = detallecuotas;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCOMPROBANTE")
	public Comprobantepago getComprobantepago() {
		return comprobantepago;
	}


	public void setComprobantepago(Comprobantepago comprobantepago) {
		this.comprobantepago = comprobantepago;
	}

	 @Column(name="ESTADO", length=10)
	public String getEstado() {
		return estado;
	}


	public void setEstado(String estado) {
		this.estado = estado;
	}

	 @Column(name="OBSERVACION", length=400)
	public String getObservacion() {
		return observacion;
	}


	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name="MONTOPENALIZACION", precision=53, scale=0)
	public Double getMontopenalizacion() {
		return montopenalizacion;
	}


	public void setMontopenalizacion(Double montopenalizacion) {
		this.montopenalizacion = montopenalizacion;
	}


   
    


}


