package pe.gob.sblm.sgi.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * Cuota generated by hbm2java
 */
@Entity
@Table(name="CUOTA_ARBITRIO"
    ,schema="dbo"
    ,catalog="sisinmueble"
)

public class Cuota_arbitrio {

     private int idcuota_arbitrio;
     private Arbitrio arbitrio;//idarbitrio
//     private Double montosoles;
//     private Double morasoles;
     private String usrcre;
     private String usrmod;
     private Date feccre;
     private Date fecmod;
     private String cancelado;
//     private String cuotanumero;
     private Integer nropagos;
//     private Integer aniocuotames;
//     private String mespagado;
     private Integer periodo;//periodo
     private Integer trimestre;//trimestre
     private String mes ;//mes
     private Double monto;//monto
     private String estado;//estado
     private String observacion;//observacion
     
//     private Double tipocambio;
     private Integer nromes;
     //private MaeDetalleCondicion maeDetalleCondicion;
     private Set<Detallecuota_arbitrio> detallecuotas = new HashSet<Detallecuota_arbitrio>(0);
     private Comprobantepago comprobantepago;
   
     
     public Cuota_arbitrio(){
    	 
     }
     @Id 
     @GeneratedValue
    @Column(name="IDCUOTA_ARBITRIO", unique=true, nullable=false)
	public int getIdcuota_arbitrio() {
		return idcuota_arbitrio;
	}
	public void setIdcuota_arbitrio(int idcuota_arbitrio) {
		this.idcuota_arbitrio = idcuota_arbitrio;
	}
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDARBITRIO", nullable=false)
	public Arbitrio getArbitrio() {
		return arbitrio;
	}
	public void setArbitrio(Arbitrio arbitrio) {
		this.arbitrio = arbitrio;
	}
//	@Column(name="MONTOSOLES", precision=53, scale=0)
//	public Double getMontosoles() {
//		return montosoles;
//	}
//	public void setMontosoles(Double montosoles) {
//		this.montosoles = montosoles;
//	}
//	 @Column(name="MORASOLES", precision=53, scale=0)
//	public Double getMorasoles() {
//		return morasoles;
//	}
//	public void setMorasoles(Double morasoles) {
//		this.morasoles = morasoles;
//	}
	 @Column(name="USRCRE", length=50)
	public String getUsrcre() {
		return usrcre;
	}
	public void setUsrcre(String usrcre) {
		this.usrcre = usrcre;
	}
	 @Column(name="USRMOD", length=50)
	public String getUsrmod() {
		return usrmod;
	}
	public void setUsrmod(String usrmod) {
		this.usrmod = usrmod;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="FECCRE", length=23)
	public Date getFeccre() {
		return feccre;
	}
	public void setFeccre(Date feccre) {
		this.feccre = feccre;
	}
	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECMOD", length=23)
	public Date getFecmod() {
		return fecmod;
	}
	public void setFecmod(Date fecmod) {
		this.fecmod = fecmod;
	}
	 @Column(name="CANCELADO")
	public String getCancelado() {
		return cancelado;
	}
	public void setCancelado(String cancelado) {
		this.cancelado = cancelado;
	}
//	  @Column(name="CUOTANUMERO", length=12)
//	public String getCuotanumero() {
//		return cuotanumero;
//	}
//	public void setCuotanumero(String cuotanumero) {
//		this.cuotanumero = cuotanumero;
//	}
//	
	 @Column(name="NROPAGOS")
	public Integer getNropagos() {
		return nropagos;
	}
	public void setNropagos(Integer nropagos) {
		this.nropagos = nropagos;
	}
	@Column(name="NROMES")
	public Integer getNromes() {
		return nromes;
	}
	public void setNromes(Integer nromes) {
		this.nromes = nromes;
	}
	
//	@Column(name="ANIOCUOTAMES")
//	public Integer getAniocuotames() {
//		return aniocuotames;
//	}
//	public void setAniocuotames(Integer aniocuotames) {
//		this.aniocuotames = aniocuotames;
//	}
//	 @Column(name="MESPAGADO")
//	public String getMespagado() {
//		return mespagado;
//	}
//	public void setMespagado(String mespagado) {
//		this.mespagado = mespagado;
//	}
	 @Column(name="PERIODO")
	 public Integer getPeriodo() {
		return periodo;
	}
	public void setPeriodo(Integer periodo) {
		this.periodo = periodo;
	}
//	@Column(name="TIPOCAMBIO", precision=53, scale=0)
//	public Double getTipocambio() {
//		return tipocambio;
//	}
//	public void setTipocambio(Double tipocambio) {
//		this.tipocambio = tipocambio;
//	}
	@OneToMany(fetch=FetchType.LAZY, mappedBy="cuota_arbitrio")
	public Set<Detallecuota_arbitrio> getDetallecuotas() {
		return detallecuotas;
	}
	public void setDetallecuotas(Set<Detallecuota_arbitrio> detallecuotas) {
		this.detallecuotas = detallecuotas;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="IDCOMPROBANTE")
	public Comprobantepago getComprobantepago() {
		return comprobantepago;
	}

	public void setComprobantepago(Comprobantepago comprobantepago) {
		this.comprobantepago = comprobantepago;
	}
	 @Column(name="TRIMESTRE")
	public Integer getTrimestre() {
		return trimestre;
	}
	public void setTrimestre(Integer trimestre) {
		this.trimestre = trimestre;
	}
	 @Column(name="MES")
	public String getMes() {
		return mes;
	}
	public void setMes(String mes) {
		this.mes = mes;
	}
	 @Column(name="MONTO")
	public Double getMonto() {
		return monto;
	}
	public void setMonto(Double monto) {
		this.monto = monto;
	}
	 @Column(name="ESTADO")
	public String getEstado() {
		return estado;
	}
	public void setEstado(String estado) {
		this.estado = estado;
	}
	 @Column(name="OBSERVACION")
	public String getObservacion() {
		return observacion;
	}
	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	
}
