package pe.gob.sblm.sgi.entity;

// Generated 20/12/2013 11:02:53 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallesegcontrato generated by hbm2java
 */
@Entity
@Table(name = "DETALLESEGCONTRATO", schema = "dbo", catalog = "sisinmueble")
public class Detallesegcontrato implements java.io.Serializable {

	private int iddetallesegcontrato;
	private Seguimientocontrato seguimientocontrato;
	private Requisito requisito;
	private Boolean activado;

	public Detallesegcontrato() {
	}

	public Detallesegcontrato(int iddetallesegcontrato) {
		this.iddetallesegcontrato = iddetallesegcontrato;
	}

	public Detallesegcontrato(int iddetallesegcontrato,
			Seguimientocontrato seguimientocontrato, Requisito requisito,
			Boolean activado) {
		this.iddetallesegcontrato = iddetallesegcontrato;
		this.seguimientocontrato = seguimientocontrato;
		this.requisito = requisito;
		this.activado = activado;
	}

	@Id
	@Column(name = "IDDETALLESEGCONTRATO", unique = true, nullable = false)
	public int getIddetallesegcontrato() {
		return this.iddetallesegcontrato;
	}

	public void setIddetallesegcontrato(int iddetallesegcontrato) {
		this.iddetallesegcontrato = iddetallesegcontrato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDSEGCONTRATO")
	public Seguimientocontrato getSeguimientocontrato() {
		return this.seguimientocontrato;
	}

	public void setSeguimientocontrato(Seguimientocontrato seguimientocontrato) {
		this.seguimientocontrato = seguimientocontrato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDREQUISITO")
	public Requisito getRequisito() {
		return this.requisito;
	}

	public void setRequisito(Requisito requisito) {
		this.requisito = requisito;
	}

	@Column(name = "ACTIVADO")
	public Boolean getActivado() {
		return this.activado;
	}

	public void setActivado(Boolean activado) {
		this.activado = activado;
	}

}
