package pe.gob.sblm.sgi.entity;

// Generated 14-oct-2013 14:58:03 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detallearbitrio generated by hbm2java
 */
@Entity
@Table(name = "DETALLEARBITRIO", schema = "dbo", catalog = "sisinmueble")
public class Detallearbitrio implements java.io.Serializable {

	private int iddetallearbitrio;
	private Arbitrio arbitrio;
	private String mes;
	private String nrorecibo;
	private int secuencia;
	private Double insoluto;
	private Double mora;
	private Date fechavencimiento;
	private String observacion;
	private Date feccre;
	private Date fecmod;
	private String usrcre;
	private String usrmod;
	

	public Detallearbitrio() {
	}

	public Detallearbitrio(int iddetallearbitrio) {
		this.iddetallearbitrio = iddetallearbitrio;
	}

	public Detallearbitrio(int iddetallearbitrio, Usuario usuario,Boolean moneda, 
			Arbitrio arbitrio, Double montopagado, Integer anio,
			String periodo, Date fecharegistro, String periodoanio,
			String periodofinal, String periodoinicial, String observacion) {
		this.iddetallearbitrio = iddetallearbitrio;
		this.arbitrio = arbitrio;
		this.observacion = observacion;
	}

	@Id @GeneratedValue
	@Column(name = "IDDETALLEARBITRIO", unique = true, nullable = false)
	public int getIddetallearbitrio() {
		return this.iddetallearbitrio;
	}

	public void setIddetallearbitrio(int iddetallearbitrio) {
		this.iddetallearbitrio = iddetallearbitrio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDARBITRIO")
	public Arbitrio getArbitrio() {
		return this.arbitrio;
	}

	public void setArbitrio(Arbitrio arbitrio) {
		this.arbitrio = arbitrio;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHAVENCIMIENTO", length = 23)
	public Date getFechavencimiento() {
		return fechavencimiento;
	}

	public void setFechavencimiento(Date fechavencimiento) {
		this.fechavencimiento = fechavencimiento;
	}


	@Column(name = "OBSERVACION", length = 100)
	public String getObservacion() {
		return this.observacion;
	}


	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "SECUENCIA")
	public int getSecuencia() {
		return secuencia;
	}

	public void setSecuencia(int secuencia) {
		this.secuencia = secuencia;
	}

    @Column(name="INSOLUTO", precision=53, scale=0)
	public Double getInsoluto() {
		return insoluto;
	}

	public void setInsoluto(Double insoluto) {
		this.insoluto = insoluto;
	}

    @Column(name="MORA", precision=53, scale=0)
	public Double getMora() {
		return mora;
	}

	public void setMora(Double mora) {
		this.mora = mora;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECCRE", length = 23)
	public Date getFeccre() {
		return feccre;
	}

	public void setFeccre(Date feccre) {
		this.feccre = feccre;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECMOD", length = 23)
	public Date getFecmod() {
		return fecmod;
	}

	public void setFecmod(Date fecmod) {
		this.fecmod = fecmod;
	}
	
	@Column(name = "USRCRE", length = 100)
	public String getUsrcre() {
		return usrcre;
	}

	public void setUsrcre(String usrcre) {
		this.usrcre = usrcre;
	}
	
	@Column(name = "USRMOD", length = 100)
	public String getUsrmod() {
		return usrmod;
	}

	public void setUsrmod(String usrmod) {
		this.usrmod = usrmod;
	}
	
	@Column(name = "MES", length = 50)
	public String getMes() {
		return mes;
	}

	public void setMes(String mes) {
		this.mes = mes;
	}
	
	@Column(name = "NRORECIBO", length = 50)
	public String getNrorecibo() {
		return nrorecibo;
	}

	public void setNrorecibo(String nrorecibo) {
		this.nrorecibo = nrorecibo;
	}
	
	
}
