package pe.gob.sblm.sgi.entity;

// Generated 05/12/2013 03:02:50 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detalletiporequisito generated by hbm2java
 */
@Entity
@Table(name = "DETALLETIPOREQUISITO", schema = "dbo", catalog = "sisinmueble")
public class Detalletiporequisito implements java.io.Serializable {

	private int iddetalletiporequisito;
	private Tiporequisito tiporequisito;
	private String descripcion;
	private Boolean estado;

	public Detalletiporequisito() {
	}

	public Detalletiporequisito(int iddetalletiporequisito) {
		this.iddetalletiporequisito = iddetalletiporequisito;
	}

	public Detalletiporequisito(int iddetalletiporequisito,
			Tiporequisito tiporequisito, String descripcion, Boolean estado) {
		this.iddetalletiporequisito = iddetalletiporequisito;
		this.tiporequisito = tiporequisito;
		this.descripcion = descripcion;
		this.estado = estado;
	}

	@Id
	@Column(name = "IDDETALLETIPOREQUISITO", unique = true, nullable = false)
	public int getIddetalletiporequisito() {
		return this.iddetalletiporequisito;
	}

	public void setIddetalletiporequisito(int iddetalletiporequisito) {
		this.iddetalletiporequisito = iddetalletiporequisito;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDTIPOREQUISITO")
	public Tiporequisito getTiporequisito() {
		return this.tiporequisito;
	}

	public void setTiporequisito(Tiporequisito tiporequisito) {
		this.tiporequisito = tiporequisito;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTADO")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

}
