package pe.gob.sblm.sgi.entity;
// Generated 19/03/2014 03:10:50 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detallecartera generated by hbm2java
 */
@Entity
@Table(name="DETALLECARTERA"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class Detallecartera  implements java.io.Serializable {


     private int iddetallecartera;
     private Cartera cartera;
     private Contrato contrato;
     private String usrcre;
     private String usrmod;
     private Date feccre;
     private Date fecmod;
     private Date fechavencimiento;
     private Set<Comprobantepago> comprobantepagos = new HashSet<Comprobantepago>(0);

    public Detallecartera() {
    }

	
    public Detallecartera(int iddetallecartera) {
        this.iddetallecartera = iddetallecartera;
    }
    public Detallecartera(int iddetallecartera, Cartera cartera, Contrato contrato, String usrcre, String usrmod, Date feccre, Date fecmod, Date fechavencimiento,  Set<Comprobantepago> comprobantepagos) {
       this.iddetallecartera = iddetallecartera;
       this.cartera = cartera;
       this.contrato = contrato;
       this.usrcre = usrcre;
       this.usrmod = usrmod;
       this.feccre = feccre;
       this.fecmod = fecmod;
       this.fechavencimiento = fechavencimiento;
       this.comprobantepagos = comprobantepagos;
    }
   
     @Id 
     @GeneratedValue
    @Column(name="IDDETALLECARTERA", unique=true, nullable=false)
    public int getIddetallecartera() {
        return this.iddetallecartera;
    }
    
    public void setIddetallecartera(int iddetallecartera) {
        this.iddetallecartera = iddetallecartera;
    }
    @ManyToOne(fetch=FetchType.LAZY)	
    @JoinColumn(name="IDCARTERA")
    public Cartera getCartera() {
        return this.cartera;
    }
    
    public void setCartera(Cartera cartera) {
        this.cartera = cartera;
    }
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCONTRATO")
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }

    @Column(name="USRCRE", length=100)
    public String getUsrcre() {
        return this.usrcre;
    }
    
    public void setUsrcre(String usrcre) {
        this.usrcre = usrcre;
    }
    
    @Column(name="USRMOD", length=100)
    public String getUsrmod() {
        return this.usrmod;
    }
    
    public void setUsrmod(String usrmod) {
        this.usrmod = usrmod;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECCRE", length=23)
    public Date getFeccre() {
        return this.feccre;
    }
    
    public void setFeccre(Date feccre) {
        this.feccre = feccre;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECMOD", length=23)
    public Date getFecmod() {
        return this.fecmod;
    }
    
    public void setFecmod(Date fecmod) {
        this.fecmod = fecmod;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAVENCIMIENTO", length=23)
    public Date getFechavencimiento() {
        return this.fechavencimiento;
    }
    
    public void setFechavencimiento(Date fechavencimiento) {
        this.fechavencimiento = fechavencimiento;
    }
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detallecartera")
    public Set<Comprobantepago> getComprobantepagos() {
        return this.comprobantepagos;
    }
    
    public void setComprobantepagos(Set<Comprobantepago> comprobantepagos) {
        this.comprobantepagos = comprobantepagos;
    }




}


