package pe.gob.sblm.sgi.entity;
// Generated 20-dic-2015 10:51:23 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Inmueblesaneamiento generated by hbm2java
 */
@Entity
@Table(name="INMUEBLESANEAMIENTO"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class Inmueblesaneamiento  implements java.io.Serializable {


     private int idinmueblesaneamiento;
     private Inmueblemaestro inmueble;
     private Saneamiento saneamiento;
     private Boolean activo;

    public Inmueblesaneamiento() {
    }

	
    public Inmueblesaneamiento(int idinmueblesaneamiento) {
        this.idinmueblesaneamiento = idinmueblesaneamiento;
    }
    public Inmueblesaneamiento(int idinmueblesaneamiento, Inmueblemaestro inmueble, Saneamiento saneamiento, Boolean activo) {
       this.idinmueblesaneamiento = idinmueblesaneamiento;
       this.inmueble = inmueble;
       this.saneamiento = saneamiento;
       this.activo = activo;
    }
   
     @Id 
     @GeneratedValue
    @Column(name="IDINMUEBLESANEAMIENTO", unique=true, nullable=false)
    public int getIdinmueblesaneamiento() {
        return this.idinmueblesaneamiento;
    }
    
    public void setIdinmueblesaneamiento(int idinmueblesaneamiento) {
        this.idinmueblesaneamiento = idinmueblesaneamiento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDINMUEBLE")
    public Inmueblemaestro getInmueble() {
        return this.inmueble;
    }
    
    public void setInmueble(Inmueblemaestro inmueble) {
        this.inmueble = inmueble;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDSANEAMIENTO")
    public Saneamiento getSaneamiento() {
        return this.saneamiento;
    }
    
    public void setSaneamiento(Saneamiento saneamiento) {
        this.saneamiento = saneamiento;
    }

    
    @Column(name="ACTIVO")
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }




}


