package pe.gob.sblm.sgi.entity;
// Generated 19/03/2014 03:10:50 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inquilino generated by hbm2java
 */
@Entity
@Table(name="INQUILINO"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class Inquilino  implements java.io.Serializable {


     private int idinquilino;
     private Tipoentidad tipoentidad;
     private Tipopersona tipopersona;
     private String razonsocial;
     private String apellidopat;
     private String apellidomat;
     private String nombre;
     private String dni;
     private String ruc;
     private String carnetextranjeria;
     private String direccion;
     private String referencia;
     private String dpto;
     private String provincia;
     private String distrito;
     private String telefono;
     private String celular;
     private String paginaweb;
     private String email;
     private String estado;
     private String concepto;
     private Integer calificacion;
     private String usrcre;
     private String usrmod;
     private Date feccre;
     private Date fecmod;
     private Boolean opchabilitado;
     private Boolean sifallecido;
     private String nombrescompletos;
     private String usr_anula;
     private Date fec_anula;
     private String host_ip_anula;
     private String motivo_anulacion;
     private Boolean sianulado;
     
     private Set<Contrato> contratos = new HashSet<Contrato>(0);

    public Inquilino() {
    }

	
    public Inquilino(int idinquilino) {
        this.idinquilino = idinquilino;
    }
    public Inquilino(int idinquilino, Tipoentidad tipoentidad, Tipopersona tipopersona, String razonsocial, String apellidopat, String apellidomat, String nombre, String dni, String ruc, String carnetextranjeria, String direccion, String referencia, String dpto, String provincia, String distrito, String telefono, String celular, String paginaweb, String email, String estado, String concepto, Integer calificacion, String usrcre, String usrmod, Date feccre, Date fecmod, Boolean opchabilitado, String nombrescompletos, Set<Contrato> contratos) {
       this.idinquilino = idinquilino;
       this.tipoentidad = tipoentidad;
       this.tipopersona = tipopersona;
       this.razonsocial = razonsocial;
       this.apellidopat = apellidopat;
       this.apellidomat = apellidomat;
       this.nombre = nombre;
       this.dni = dni;
       this.ruc = ruc;
       this.carnetextranjeria = carnetextranjeria;
       this.direccion = direccion;
       this.referencia = referencia;
       this.dpto = dpto;
       this.provincia = provincia;
       this.distrito = distrito;
       this.telefono = telefono;
       this.celular = celular;
       this.paginaweb = paginaweb;
       this.email = email;
       this.estado = estado;
       this.concepto = concepto;
       this.calificacion = calificacion;
       this.usrcre = usrcre;
       this.usrmod = usrmod;
       this.feccre = feccre;
       this.fecmod = fecmod;
       this.opchabilitado = opchabilitado;
       this.nombrescompletos = nombrescompletos;
       this.contratos = contratos;
    }
   
     @Id 
     @GeneratedValue
    @Column(name="IDINQUILINO", unique=true, nullable=false)
    public int getIdinquilino() {
        return this.idinquilino;
    }
    
    public void setIdinquilino(int idinquilino) {
        this.idinquilino = idinquilino;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPOENTIDAD")
    public Tipoentidad getTipoentidad() {
        return this.tipoentidad;
    }
    
    public void setTipoentidad(Tipoentidad tipoentidad) {
        this.tipoentidad = tipoentidad;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPOPERSONA")
    public Tipopersona getTipopersona() {
        return this.tipopersona;
    }
    
    public void setTipopersona(Tipopersona tipopersona) {
        this.tipopersona = tipopersona;
    }
    
    @Column(name="RAZONSOCIAL", length=100)
    public String getRazonsocial() {
        return this.razonsocial;
    }
    
    public void setRazonsocial(String razonsocial) {
        this.razonsocial = razonsocial;
    }
    
    @Column(name="APELLIDOPAT", length=50)
    public String getApellidopat() {
        return this.apellidopat;
    }
    
    public void setApellidopat(String apellidopat) {
        this.apellidopat = apellidopat;
    }
    
    @Column(name="APELLIDOMAT", length=50)
    public String getApellidomat() {
        return this.apellidomat;
    }
    
    public void setApellidomat(String apellidomat) {
        this.apellidomat = apellidomat;
    }
    
    @Column(name="NOMBRE", length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="DNI", length=8)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    
    @Column(name="RUC", length=20)
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    
    @Column(name="CARNETEXTRANJERIA", length=20)
    public String getCarnetextranjeria() {
        return this.carnetextranjeria;
    }
    
    public void setCarnetextranjeria(String carnetextranjeria) {
        this.carnetextranjeria = carnetextranjeria;
    }
    
    @Column(name="DIRECCION", length=100)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="REFERENCIA", length=100)
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    
    @Column(name="DPTO", length=100)
    public String getDpto() {
        return this.dpto;
    }
    
    public void setDpto(String dpto) {
        this.dpto = dpto;
    }
    
    @Column(name="PROVINCIA", length=100)
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    
    @Column(name="DISTRITO", length=100)
    public String getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(String distrito) {
        this.distrito = distrito;
    }
    
    @Column(name="TELEFONO", length=10)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="CELULAR", length=9)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    
    @Column(name="PAGINAWEB", length=200)
    public String getPaginaweb() {
        return this.paginaweb;
    }
    
    public void setPaginaweb(String paginaweb) {
        this.paginaweb = paginaweb;
    }
    
    @Column(name="EMAIL", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="ESTADO", length=50)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name="CONCEPTO", length=100)
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    
    @Column(name="CALIFICACION")
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }
    
    @Column(name="USRCRE", length=100)
    public String getUsrcre() {
        return this.usrcre;
    }
    
    public void setUsrcre(String usrcre) {
        this.usrcre = usrcre;
    }
    
    @Column(name="USRMOD", length=100)
    public String getUsrmod() {
        return this.usrmod;
    }
    
    public void setUsrmod(String usrmod) {
        this.usrmod = usrmod;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECCRE", length=23)
    public Date getFeccre() {
        return this.feccre;
    }
    
    public void setFeccre(Date feccre) {
        this.feccre = feccre;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECMOD", length=23)
    public Date getFecmod() {
        return this.fecmod;
    }
    
    public void setFecmod(Date fecmod) {
        this.fecmod = fecmod;
    }
    
    @Column(name="OPCHABILITADO")
    public Boolean getOpchabilitado() {
        return this.opchabilitado;
    }
    
    public void setOpchabilitado(Boolean opchabilitado) {
        this.opchabilitado = opchabilitado;
    }
    
    @Column(name="SIFALLECIDO")   
    public Boolean getSifallecido() {
		return sifallecido;
	}


	public void setSifallecido(Boolean sifallecido) {
		this.sifallecido = sifallecido;
	}


	@Column(name="NOMBRESCOMPLETOS", length=150)
    public String getNombrescompletos() {
        return this.nombrescompletos;
    }
    
    public void setNombrescompletos(String nombrescompletos) {
        this.nombrescompletos = nombrescompletos;
    }
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="inquilino")
    public Set<Contrato> getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set<Contrato> contratos) {
        this.contratos = contratos;
    }

    @Column(name="USR_ANULA")
	public String getUsr_anula() {
		return usr_anula;
	}


	public void setUsr_anula(String usr_anula) {
		this.usr_anula = usr_anula;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_ANULA", length=23)
	public Date getFec_anula() {
		return fec_anula;
	}


	public void setFec_anula(Date fec_anula) {
		this.fec_anula = fec_anula;
	}

    @Column(name="HOST_IP_ANULA")
	public String getHost_ip_anula() {
		return host_ip_anula;
	}


	public void setHost_ip_anula(String host_ip_anula) {
		this.host_ip_anula = host_ip_anula;
	}

    @Column(name="MOTIVO_ANULACION",length=200)
	public String getMotivo_anulacion() {
		return motivo_anulacion;
	}


	public void setMotivo_anulacion(String motivo_anulacion) {
		this.motivo_anulacion = motivo_anulacion;
	}

    @Column(name="SIANULADO")
	public Boolean getSianulado() {
		return sianulado;
	}


	public void setSianulado(Boolean sianulado) {
		this.sianulado = sianulado;
	}
    
   


}


