package pe.gob.sblm.sgi.entity;
// Generated 04/07/2014 12:01:46 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Letra generated by hbm2java
 */
@Entity
@Table(name="LETRA"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class Letra  implements java.io.Serializable {


     private int idletra;
     private Contrato contrato;
     private Double monto;
     private Boolean status;
     private String nrocomprobante;
     private int numero;
     private String secuencia;
     private Date fechagiro;
     private Date fechavencimiento;
     private String mes;
     private int anio;

    public Letra() {
    }

	
    public Letra(int idletra) {
        this.idletra = idletra;
    }
    public Letra(int idletra, Contrato contrato, Double monto, Boolean status, String nrocomprobante, Date fechagiro, Date fechavencimiento) {
       this.idletra = idletra;
       this.contrato = contrato;
       this.monto = monto;
       this.status = status;
       this.nrocomprobante = nrocomprobante;
       this.fechagiro = fechagiro;
       this.fechavencimiento = fechavencimiento;
    }
   
     @Id 
     @GeneratedValue
    @Column(name="IDLETRA", unique=true, nullable=false)
    public int getIdletra() {
        return this.idletra;
    }
    
    public void setIdletra(int idletra) {
        this.idletra = idletra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCONTRATO")
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }

    
    @Column(name="MONTO", precision=53, scale=0)
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }

    
    @Column(name="STATUS")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

    
    @Column(name="NROCOMPROBANTE", length=50)
    public String getNrocomprobante() {
        return this.nrocomprobante;
    }
    
    public void setNrocomprobante(String nrocomprobante) {
        this.nrocomprobante = nrocomprobante;
    }
    
    
    @Column(name="NUMERO")
    public int getNumero() {
		return numero;
	}


	public void setNumero(int numero) {
		this.numero = numero;
	}

    @Column(name="SECUENCIA", length=10)
	public String getSecuencia() {
		return secuencia;
	}


	public void setSecuencia(String secuencia) {
		this.secuencia = secuencia;
	}
	
	

    @Column(name="MES", length=10)
	public String getMes() {
		return mes;
	}


	public void setMes(String mes) {
		this.mes = mes;
	}

    @Column(name="ANIO")
	public int getAnio() {
		return anio;
	}


	public void setAnio(int anio) {
		this.anio = anio;
	}


	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAGIRO", length=23)
    public Date getFechagiro() {
        return this.fechagiro;
    }
    
    public void setFechagiro(Date fechagiro) {
        this.fechagiro = fechagiro;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAVENCIMIENTO", length=23)
    public Date getFechavencimiento() {
        return this.fechavencimiento;
    }
    
    public void setFechavencimiento(Date fechavencimiento) {
        this.fechavencimiento = fechavencimiento;
    }




}


