package pe.gob.sblm.sgi.entity;

// Generated 14-oct-2013 14:58:03 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Accion generated by hbm2java
 */
@Entity
@Table(name = "MAE_ACCION", schema = "dbo", catalog = "sisinmueble")
public class MaeAccion implements java.io.Serializable {

	private int idaccion;
	private String descripcion;
	private String nombre;
	private Boolean estado;

	public MaeAccion() {
	}

	public MaeAccion(int idaccion) {
		this.idaccion = idaccion;
	}

	public MaeAccion(int idaccion, String descripcion, String nombre,
			Boolean estado, String codigoaccion) {
		this.idaccion = idaccion;
		this.descripcion = descripcion;
		this.nombre = nombre;
		this.estado = estado;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID_ACCION", unique = true, nullable = false)
	public int getIdaccion() {
		return this.idaccion;
	}

	public void setIdaccion(int idaccion) {
		this.idaccion = idaccion;
	}
	
	@Column(name = "NOMBRE", length = 50, nullable = false)
	public String getNombre() {
		return nombre;
	}

	
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	@Column(name = "DESCRIPCION", length = 100, nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}


	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTADO", nullable = false)
	public Boolean getEstado() {
		return estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

}
