package pe.gob.sblm.sgi.entity;
// Generated 20-ene-2018 0:10:48 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.annotation.Generated;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MaeDetalleCondicion generated by hbm2java
 */
@Entity
@Table(name="MAE_DETALLE_CONDICION"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class MaeDetalleCondicion  implements java.io.Serializable {


     private int idDetalleCondicion;
     private Contrato contrato;
     private String mes;
     private String anio;
     private Double contraprestacion;
     private Double renta;
     private Double montopagar;
     private Boolean siclausulareconocimientorenta;
     private Boolean siclausulaperiodogracia;
     private Boolean siclausulareconocimientoinversion;
     private Boolean siclausulapagoposterior;
     private Double montopagoposterior;
     private String observacionpagoposterior;
     private Double descuentoreconocimientorenta;
     private String observacionreconocimientorenta;
     
     private Boolean siclausulasuspensiontemporalrenta;
     private Double montosuspensiontemporalrenta;
     private String observacionsuspensiontemporalrenta;
     
     
     private Boolean sipagofraccionrenta;
     private Integer secuencia;
     
     private Integer numeromes;
     
     private Boolean sirentagenerada;
     
     private String estado;
     
     private Set<MaeDetCondicionDetalle> maedetcondiciondetalles = new HashSet<MaeDetCondicionDetalle>(0);
     //
     private String nrocuota;
     private Date fechavencimiento;
     private Boolean sianulado;
     private String usr_cre;
     private Date fec_cre;
     private String obs_cre;
     private String host_ip_cre;
     private String usr_mod;
     private Date fec_mod;
     private String motivo_mod;
     private String host_ip_mod;
     private String usr_anula;
     private Date fec_anula;
     private String motivo_anula;
     private String host_ip_anula;
     
    public MaeDetalleCondicion() {
    }

	
    public MaeDetalleCondicion(int idDetalleCondicion, Contrato contrato) {
        this.idDetalleCondicion = idDetalleCondicion;
        this.contrato = contrato;
    }
    public MaeDetalleCondicion(int idDetalleCondicion, Contrato contrato, String mes, String anio, Double contraprestacion, Double renta, Double montopagar, Boolean siclausulareconocimientorenta, Boolean siclausulaperiodogracia, Boolean siclausulareconocimientoinversion, String siclausulatipopagoposterior, Double montopagoposterior, String observacionpagoposterior, Double descuentoreconocimientorenta, String observacionreconocimientorenta) {
       this.idDetalleCondicion = idDetalleCondicion;
       this.contrato = contrato;
       this.mes = mes;
       this.anio = anio;
       this.contraprestacion = contraprestacion;
       this.renta = renta;
       this.montopagar = montopagar;
       this.siclausulareconocimientorenta = siclausulareconocimientorenta;
       this.siclausulaperiodogracia = siclausulaperiodogracia;
       this.siclausulareconocimientoinversion = siclausulareconocimientoinversion;
       this.siclausulapagoposterior = siclausulapagoposterior;
       this.montopagoposterior = montopagoposterior;
       this.observacionpagoposterior = observacionpagoposterior;
       this.descuentoreconocimientorenta = descuentoreconocimientorenta;
       this.observacionreconocimientorenta = observacionreconocimientorenta;
    }
   
     @Id 

    @GeneratedValue
    @Column(name="ID_DETALLE_CONDICION", unique=true, nullable=false)
    public int getIdDetalleCondicion() {
        return this.idDetalleCondicion;
    }
    
    public void setIdDetalleCondicion(int idDetalleCondicion) {
        this.idDetalleCondicion = idDetalleCondicion;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCONTRATO", nullable=false)
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }

    
    @Column(name="MES", length=12)
    public String getMes() {
        return this.mes;
    }
    
    public void setMes(String mes) {
        this.mes = mes;
    }

    
    @Column(name="ANIO", length=4)
    public String getAnio() {
        return this.anio;
    }
    
    public void setAnio(String anio) {
        this.anio = anio;
    }

    
    @Column(name="CONTRAPRESTACION", precision=53, scale=0)
    public Double getContraprestacion() {
        return this.contraprestacion;
    }
    
    public void setContraprestacion(Double contraprestacion) {
        this.contraprestacion = contraprestacion;
    }

    
    @Column(name="RENTA", precision=53, scale=0)
    public Double getRenta() {
        return this.renta;
    }
    
    public void setRenta(Double renta) {
        this.renta = renta;
    }

    
    @Column(name="MONTOPAGAR", precision=53, scale=0)
    public Double getMontopagar() {
        return this.montopagar;
    }
    
    public void setMontopagar(Double montopagar) {
        this.montopagar = montopagar;
    }

    
    @Column(name="SICLAUSULARECONOCIMIENTORENTA")
    public Boolean getSiclausulareconocimientorenta() {
        return this.siclausulareconocimientorenta;
    }
    
    public void setSiclausulareconocimientorenta(Boolean siclausulareconocimientorenta) {
        this.siclausulareconocimientorenta = siclausulareconocimientorenta;
    }

    
    @Column(name="SICLAUSULAPERIODOGRACIA")
    public Boolean getSiclausulaperiodogracia() {
        return this.siclausulaperiodogracia;
    }
    
    public void setSiclausulaperiodogracia(Boolean siclausulaperiodogracia) {
        this.siclausulaperiodogracia = siclausulaperiodogracia;
    }

    
    @Column(name="SICLAUSULARECONOCIMIENTOINVERSION")
    public Boolean getSiclausulareconocimientoinversion() {
        return this.siclausulareconocimientoinversion;
    }
    
    public void setSiclausulareconocimientoinversion(Boolean siclausulareconocimientoinversion) {
        this.siclausulareconocimientoinversion = siclausulareconocimientoinversion;
    }

    
    @Column(name="SICLAUSULAPAGOPOSTERIOR")
    public Boolean getSiclausulapagoposterior() {
		return siclausulapagoposterior;
	}


	public void setSiclausulapagoposterior(Boolean siclausulapagoposterior) {
		this.siclausulapagoposterior = siclausulapagoposterior;
	}

    
    @Column(name="MONTOPAGOPOSTERIOR", precision=53, scale=0)
    public Double getMontopagoposterior() {
        return this.montopagoposterior;
    }
    
	public void setMontopagoposterior(Double montopagoposterior) {
        this.montopagoposterior = montopagoposterior;
    }

    
    @Column(name="OBSERVACIONPAGOPOSTERIOR", length=50)
    public String getObservacionpagoposterior() {
        return this.observacionpagoposterior;
    }
    
    public void setObservacionpagoposterior(String observacionpagoposterior) {
        this.observacionpagoposterior = observacionpagoposterior;
    }

    
    @Column(name="DESCUENTORECONOCIMIENTORENTA", precision=53, scale=0)
    public Double getDescuentoreconocimientorenta() {
        return this.descuentoreconocimientorenta;
    }
    
    public void setDescuentoreconocimientorenta(Double descuentoreconocimientorenta) {
        this.descuentoreconocimientorenta = descuentoreconocimientorenta;
    }

    
    @Column(name="OBSERVACIONRECONOCIMIENTORENTA", length=50)
    public String getObservacionreconocimientorenta() {
        return this.observacionreconocimientorenta;
    }
    
    public void setObservacionreconocimientorenta(String observacionreconocimientorenta) {
        this.observacionreconocimientorenta = observacionreconocimientorenta;
    }

    
    @Column(name="SIPAGOFRACCIONRENTA")
	public Boolean getSipagofraccionrenta() {
		return sipagofraccionrenta;
	}


	public void setSipagofraccionrenta(Boolean sipagofraccionrenta) {
		this.sipagofraccionrenta = sipagofraccionrenta;
	}


    @Column(name="SECUENCIA")
	public Integer getSecuencia() {
		return secuencia;
	}


	public void setSecuencia(Integer secuencia) {
		this.secuencia = secuencia;
	}

    @Column(name="NUMEROMES")
	public Integer getNumeromes() {
		return numeromes;
	}


	public void setNumeromes(Integer numeromes) {
		this.numeromes = numeromes;
	}

    @Column(name="SIRENTAGENERADA")
	public Boolean getSirentagenerada() {
		return sirentagenerada;
	}


	public void setSirentagenerada(Boolean sirentagenerada) {
		this.sirentagenerada = sirentagenerada;
	}
	

    @Column(name="SICLAUSULASUSPENSIONTEMPORALRENTA")
	public Boolean getSiclausulasuspensiontemporalrenta() {
		return siclausulasuspensiontemporalrenta;
	}


	public void setSiclausulasuspensiontemporalrenta(Boolean siclausulasuspensiontemporalrenta) {
		this.siclausulasuspensiontemporalrenta = siclausulasuspensiontemporalrenta;
	}

    @Column(name="MONTOSUSPENSIONTEMPORALRENTA", precision=53, scale=0)
	public Double getMontosuspensiontemporalrenta() {
		return montosuspensiontemporalrenta;
	}


	public void setMontosuspensiontemporalrenta(Double montosuspensiontemporalrenta) {
		this.montosuspensiontemporalrenta = montosuspensiontemporalrenta;
	}

    @Column(name="OBSERVACIONSUSPENSIONTEMPORALRENTA", length=50)
	public String getObservacionsuspensiontemporalrenta() {
		return observacionsuspensiontemporalrenta;
	}


	public void setObservacionsuspensiontemporalrenta(String observacionsuspensiontemporalrenta) {
		this.observacionsuspensiontemporalrenta = observacionsuspensiontemporalrenta;
	}

	@Column(name="ESTADO", length=10)
	public String getEstado() {
		return estado;
	}


	public void setEstado(String estado) {
		this.estado = estado;
	}
	
	@OneToMany(cascade=CascadeType.ALL ,fetch=FetchType.LAZY, mappedBy="maedetallecondicion")
	public Set<MaeDetCondicionDetalle> getMaedetcondiciondetalles() {
		return maedetcondiciondetalles;
	}


	public void setMaedetcondiciondetalles(
			Set<MaeDetCondicionDetalle> maedetcondiciondetalles) {
		this.maedetcondiciondetalles = maedetcondiciondetalles;
	}

    @Column(name="NROCUOTA" , length=3)
	public String getNrocuota() {
		return nrocuota;
	}


	public void setNrocuota(String nrocuota) {
		this.nrocuota = nrocuota;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAVENCIMIENTO", length=23)
	public Date getFechavencimiento() {
		return fechavencimiento;
	}


	public void setFechavencimiento(Date fechavencimiento) {
		this.fechavencimiento = fechavencimiento;
	}

    @Column(name="SIANULADO")
	public Boolean getSianulado() {
		return sianulado;
	}

  
	public void setSianulado(Boolean sianulado) {
		this.sianulado = sianulado;
	}

    @Column(name="USR_CRE" ,length=100)
	public String getUsr_cre() {
		return usr_cre;
	}


	public void setUsr_cre(String usr_cre) {
		this.usr_cre = usr_cre;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_CRE", length=23)
	public Date getFec_cre() {
		return fec_cre;
	}


	public void setFec_cre(Date fec_cre) {
		this.fec_cre = fec_cre;
	}

    @Column(name="OBS_CRE" ,length=1000)
	public String getObs_cre() {
		return obs_cre;
	}


	public void setObs_cre(String obs_cre) {
		this.obs_cre = obs_cre;
	}

    @Column(name="HOST_IP_CRE" , length=100)
	public String getHost_ip_cre() {
		return host_ip_cre;
	}


	public void setHost_ip_cre(String host_ip_cre) {
		this.host_ip_cre = host_ip_cre;
	}

	@Column(name="USR_MOD" ,length=100)
	public String getUsr_mod() {
		return usr_mod;
	}


	public void setUsr_mod(String usr_mod) {
		this.usr_mod = usr_mod;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_MOD", length=23)
	public Date getFec_mod() {
		return fec_mod;
	}


	public void setFec_mod(Date fec_mod) {
		this.fec_mod = fec_mod;
	}

	@Column(name="MOTIVO_MOD" ,length=1000)
	public String getMotivo_mod() {
		return motivo_mod;
	}


	public void setMotivo_mod(String motivo_mod) {
		this.motivo_mod = motivo_mod;
	}

    @Column(name="HOST_IP_MOD" , length=100)
	public String getHost_ip_mod() {
		return host_ip_mod;
	}


	public void setHost_ip_mod(String host_ip_mod) {
		this.host_ip_mod = host_ip_mod;
	}

	@Column(name="USR_ANULA" ,length=100)
	public String getUsr_anula() {
		return usr_anula;
	}


	public void setUsr_anula(String usr_anula) {
		this.usr_anula = usr_anula;
	}
 
	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_ANULA", length=23)
	public Date getFec_anula() {
		return fec_anula;
	}


	public void setFec_anula(Date fec_anula) {
		this.fec_anula = fec_anula;
	}

	@Column(name="MOTIVO_ANULA" ,length=1000)
	public String getMotivo_anula() {
		return motivo_anula;
	}


	public void setMotivo_anula(String motivo_anula) {
		this.motivo_anula = motivo_anula;
	}

    @Column(name="HOST_IP_ANULA" , length=100)
	public String getHost_ip_anula() {
		return host_ip_anula;
	}


	public void setHost_ip_anula(String host_ip_anula) {
		this.host_ip_anula = host_ip_anula;
	}
	
	
	
	
}


