package pe.gob.sblm.sgi.entity;
// Generated 19/03/2014 03:10:50 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Banco generated by hbm2java
 */
@Entity
@Table(name="MAE_IPC"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class MaeIpc  implements java.io.Serializable {


     private int idipc;
     private String anio;
     private Double valor;

    public MaeIpc() {
    }

	
    
    
	@Id 
    @Column(name="ID_IPC", unique=true, nullable=false)
     public int getIdipc() {
		return idipc;
	}


	public void setIdipc(int idipc) {
		this.idipc = idipc;
	}

    @Column(name="ANIO")
	public String getAnio() {
		return anio;
	}



	public void setAnio(String anio) {
		this.anio = anio;
	}




    @Column(name="VALOR", precision=53, scale=0)
	public Double getValor() {
		return valor;
	}


	public void setValor(Double valor) {
		this.valor = valor;
	}




	@Override
	public String toString() {
		return "MaeIpc [idipc=" + idipc + ", anio=" + anio + ", valor=" + valor
				+ "]";
	}



}


