package pe.gob.sblm.sgi.entity;
// Generated 29-ene-2017 10:59:51 by Hibernate Tools 4.3.1


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MaeNotificacion generated by hbm2java
 */
@Entity
@Table(name="MAE_NOTIFICACION"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class MaeNotificacion  implements java.io.Serializable {


     private int idNotificacion;
     private Usuario usuarioorigen;
     private Usuario usuariodestino;
     private String titulo;     
     private String mensaje;
     private String uidAlfresco;
     private Boolean estadoLeido;
     private Boolean estadoCorreoEnviado;
     private String usuarioCreador;
     private Date fechaCreacion;
     private Date fechaEnvioCorreo;
     private Boolean siNotificacionTipoReporte;

    public MaeNotificacion() {
    }

	
    public MaeNotificacion(int idNotificacion) {
        this.idNotificacion = idNotificacion;
    }
    public MaeNotificacion(int idNotificacion, Usuario usuarioorigen, String mensaje, String uidAlfresco, Boolean estadoLeido, String usuarioCreador, Date fechaCreacion,Date fechaEnvioCorreo) {
       this.idNotificacion = idNotificacion;
       this.usuarioorigen = usuarioorigen;
       this.mensaje = mensaje;
       this.uidAlfresco = uidAlfresco;
       this.estadoLeido = estadoLeido;
       this.usuarioCreador = usuarioCreador;
       this.fechaCreacion = fechaCreacion;
       this.fechaEnvioCorreo = fechaEnvioCorreo;
    }
   
     @Id 
     @GeneratedValue
    @Column(name="ID_NOTIFICACION", unique=true, nullable=false)
    public int getIdNotificacion() {
        return this.idNotificacion;
    }
    
    public void setIdNotificacion(int idNotificacion) {
        this.idNotificacion = idNotificacion;
    }


    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDUSUARIOORIGEN")
	public Usuario getUsuarioorigen() {
	return usuarioorigen;
	}
	
	
	
	public void setUsuarioorigen(Usuario usuarioorigen) {
	this.usuarioorigen = usuarioorigen;
	}
	
	
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDUSUARIODESTINO")	
	public Usuario getUsuariodestino() {
	return usuariodestino;
	}
	
	
	public void setUsuariodestino(Usuario usuariodestino) {
	this.usuariodestino = usuariodestino;
	}

	@Column(name="TITULO", length=100)   
	public String getTitulo() {
		return titulo;
	}


	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}


	@Column(name="MENSAJE", length=100)
    public String getMensaje() {
        return this.mensaje;
    }
    


	public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }

    
    @Column(name="UID_ALFRESCO", length=50)
    public String getUidAlfresco() {
        return this.uidAlfresco;
    }
    
    public void setUidAlfresco(String uidAlfresco) {
        this.uidAlfresco = uidAlfresco;
    }

    
    @Column(name="ESTADO_LEIDO")
    public Boolean getEstadoLeido() {
        return this.estadoLeido;
    }
    
    public void setEstadoLeido(Boolean estadoLeido) {
        this.estadoLeido = estadoLeido;
    }

    
    
    @Column(name="ESTADO_CORREO_ENVIADO")    
	public Boolean getEstadoCorreoEnviado() {
		return estadoCorreoEnviado;
	}


	public void setEstadoCorreoEnviado(Boolean estadoCorreoEnviado) {
		this.estadoCorreoEnviado = estadoCorreoEnviado;
	}


	@Column(name="USUARIO_CREADOR", length=50)
    public String getUsuarioCreador() {
        return this.usuarioCreador;
    }
    
    public void setUsuarioCreador(String usuarioCreador) {
        this.usuarioCreador = usuarioCreador;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHA_CREACION", length=23)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHA_ENVIO_CORREO", length=23)
	public Date getFechaEnvioCorreo() {
		return fechaEnvioCorreo;
	}

    public void setFechaEnvioCorreo(Date fechaEnvioCorreo) {
		this.fechaEnvioCorreo = fechaEnvioCorreo;
	}


	@Column(name="SINOTIFICACIONTIPOREPORTE", length=50)
	public Boolean getSiNotificacionTipoReporte() {
		return siNotificacionTipoReporte;
	}



	public void setSiNotificacionTipoReporte(Boolean siNotificacionTipoReporte) {
		this.siNotificacionTipoReporte = siNotificacionTipoReporte;
	}

}


