package pe.gob.sblm.sgi.entity;
// Generated 07-oct-2017 18:45:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MaePreSerieComprobantepago generated by hbm2java
 */
@Entity
@Table(name="MAE_PRE_SERIE_COMPROBANTEPAGO"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class MaePreSerieComprobantepago  implements java.io.Serializable {


     private int idPreSerieComprobantepago;
     private String numero;
     private Boolean estado;
     private Set<MaeSerieComprobantepago> maeSerieComprobantepagos = new HashSet<MaeSerieComprobantepago>(0);

    public MaePreSerieComprobantepago() {
    }

	
    public MaePreSerieComprobantepago(int idPreSerieComprobantepago) {
        this.idPreSerieComprobantepago = idPreSerieComprobantepago;
    }
    public MaePreSerieComprobantepago(int idPreSerieComprobantepago, String numero, Boolean estado, Set<MaeSerieComprobantepago> maeSerieComprobantepagos) {
       this.idPreSerieComprobantepago = idPreSerieComprobantepago;
       this.numero = numero;
       this.estado = estado;
       this.maeSerieComprobantepagos = maeSerieComprobantepagos;
    }
   
     @Id 

    
    @Column(name="ID_PRE_SERIE_COMPROBANTEPAGO", unique=true, nullable=false)
    public int getIdPreSerieComprobantepago() {
        return this.idPreSerieComprobantepago;
    }
    
    public void setIdPreSerieComprobantepago(int idPreSerieComprobantepago) {
        this.idPreSerieComprobantepago = idPreSerieComprobantepago;
    }

    
    @Column(name="NUMERO", length=3)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="ESTADO")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maePreSerieComprobantepago")
    public Set<MaeSerieComprobantepago> getMaeSerieComprobantepagos() {
        return this.maeSerieComprobantepagos;
    }
    
    public void setMaeSerieComprobantepagos(Set<MaeSerieComprobantepago> maeSerieComprobantepagos) {
        this.maeSerieComprobantepagos = maeSerieComprobantepagos;
    }




}


