package pe.gob.sblm.sgi.entity;
// Generated 07-oct-2017 18:45:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MaeSerieComprobantepago generated by hbm2java
 */
@Entity
@Table(name="MAE_SERIE_COMPROBANTEPAGO"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class MaeSerieComprobantepago  implements java.io.Serializable {


     private int idSerieComprobantepago;
     private Cartera cartera;
     private MaePreSerieComprobantepago maePreSerieComprobantepago;
     private Tipodocu tipodocu;
     private String serie;
     private Set<MaeNumeracionComprobantepago> maeNumeracionComprobantepagos = new HashSet<MaeNumeracionComprobantepago>(0);

    public MaeSerieComprobantepago() {
    }

	
    public MaeSerieComprobantepago(int idSerieComprobantepago) {
        this.idSerieComprobantepago = idSerieComprobantepago;
    }
    public MaeSerieComprobantepago(int idSerieComprobantepago, Cartera cartera, MaePreSerieComprobantepago maePreSerieComprobantepago, Tipodocu tipodocu, String serie, Set<MaeNumeracionComprobantepago> maeNumeracionComprobantepagos) {
       this.idSerieComprobantepago = idSerieComprobantepago;
       this.cartera = cartera;
       this.maePreSerieComprobantepago = maePreSerieComprobantepago;
       this.tipodocu = tipodocu;
       this.serie = serie;
       this.maeNumeracionComprobantepagos = maeNumeracionComprobantepagos;
    }
   
     @Id 

    
    @Column(name="ID_SERIE_COMPROBANTEPAGO", unique=true, nullable=false)
    public int getIdSerieComprobantepago() {
        return this.idSerieComprobantepago;
    }
    
    public void setIdSerieComprobantepago(int idSerieComprobantepago) {
        this.idSerieComprobantepago = idSerieComprobantepago;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCARTERA")
    public Cartera getCartera() {
        return this.cartera;
    }
    
    public void setCartera(Cartera cartera) {
        this.cartera = cartera;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PRE_SERIE_COMPROBANTEPAGO")
    public MaePreSerieComprobantepago getMaePreSerieComprobantepago() {
        return this.maePreSerieComprobantepago;
    }
    
    public void setMaePreSerieComprobantepago(MaePreSerieComprobantepago maePreSerieComprobantepago) {
        this.maePreSerieComprobantepago = maePreSerieComprobantepago;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPODOCU")
    public Tipodocu getTipodocu() {
        return this.tipodocu;
    }
    
    public void setTipodocu(Tipodocu tipodocu) {
        this.tipodocu = tipodocu;
    }

    
    @Column(name="SERIE", length=4)
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maeSerieComprobantepago")
    public Set<MaeNumeracionComprobantepago> getMaeNumeracionComprobantepagos() {
        return this.maeNumeracionComprobantepagos;
    }
    
    public void setMaeNumeracionComprobantepagos(Set<MaeNumeracionComprobantepago> maeNumeracionComprobantepagos) {
        this.maeNumeracionComprobantepagos = maeNumeracionComprobantepagos;
    }




}


