package pe.gob.sblm.sgi.entity;
// Generated 19/03/2014 03:10:50 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Materialpredominante generated by hbm2java
 */
@Entity
@Table(name="MATERIALPREDOMINANTE"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class Materialpredominante  implements java.io.Serializable {


     private int idmaterialpredominante;
     private String descripcion;
     private Boolean estado;
     private Set<Inmueble> inmuebles = new HashSet<Inmueble>(0);

    public Materialpredominante() {
    }

	
    public Materialpredominante(int idmaterialpredominante) {
        this.idmaterialpredominante = idmaterialpredominante;
    }
    public Materialpredominante(int idmaterialpredominante, String descripcion, Boolean estado, Set<Inmueble> inmuebles) {
       this.idmaterialpredominante = idmaterialpredominante;
       this.descripcion = descripcion;
       this.estado = estado;
       this.inmuebles = inmuebles;
    }
   
     @Id 
    
    @Column(name="IDMATERIALPREDOMINANTE", unique=true, nullable=false)
    public int getIdmaterialpredominante() {
        return this.idmaterialpredominante;
    }
    
    public void setIdmaterialpredominante(int idmaterialpredominante) {
        this.idmaterialpredominante = idmaterialpredominante;
    }
    
    @Column(name="DESCRIPCION", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="ESTADO")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="materialpredominante")
    public Set<Inmueble> getInmuebles() {
        return this.inmuebles;
    }
    
    public void setInmuebles(Set<Inmueble> inmuebles) {
        this.inmuebles = inmuebles;
    }




}


