package pe.gob.sblm.sgi.entity;

// Generated 20/12/2013 11:02:53 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pasoperfil generated by hbm2java
 */
@Entity
@Table(name = "PASOPERFIL", schema = "dbo", catalog = "sisinmueble")
public class Pasoperfil implements java.io.Serializable {

	private int idpasoperfil;
	private Perfil perfil;
	private String descripcion;
	private Integer nropaso;
	private Set<Seguimientocontrato> seguimientocontratos = new HashSet<Seguimientocontrato>(
			0);

	public Pasoperfil() {
	}

	public Pasoperfil(int idpasoperfil) {
		this.idpasoperfil = idpasoperfil;
	}

	public Pasoperfil(int idpasoperfil, Perfil perfil, String descripcion,
			Integer nropaso, Set<Seguimientocontrato> seguimientocontratos) {
		this.idpasoperfil = idpasoperfil;
		this.perfil = perfil;
		this.descripcion = descripcion;
		this.nropaso = nropaso;
		this.seguimientocontratos = seguimientocontratos;
	}

	@Id
	@Column(name = "IDPASOPERFIL", unique = true, nullable = false)
	public int getIdpasoperfil() {
		return this.idpasoperfil;
	}

	public void setIdpasoperfil(int idpasoperfil) {
		this.idpasoperfil = idpasoperfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPERFIL")
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "NROPASO")
	public Integer getNropaso() {
		return this.nropaso;
	}

	public void setNropaso(Integer nropaso) {
		this.nropaso = nropaso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pasoperfil")
	public Set<Seguimientocontrato> getSeguimientocontratos() {
		return this.seguimientocontratos;
	}

	public void setSeguimientocontratos(
			Set<Seguimientocontrato> seguimientocontratos) {
		this.seguimientocontratos = seguimientocontratos;
	}

}
