package pe.gob.sblm.sgi.entity;
// Generated 25/08/2014 09:36:23 AM by Hibernate Tools 3.6.0


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contrato generated by hbm2java
 */
@Entity
@Table(name="PROCESOJUDICIALUPA"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class Procesojudicialupa  implements java.io.Serializable {


     private int idprocesojudicialupa;
     private Upa upa;
     private String expediente;
     private Boolean sifinalizado;
     private String motivo;
     private String situacion;
     private Boolean sidocumento;
     private String observacion; 
     private String usrcre;
 	 private Date feccre;
 	 private String usrmod;
 	 private Date fecmod;
 	 private String observacionmodificacion;
     private String estado;
     private String host_ip_usrcre;
     private String host_ip_usrmod;
     
 	 public Procesojudicialupa(){
 		 
 	 }
     public Procesojudicialupa(int idprocesojudicialupa){
    	 this.idprocesojudicialupa=idprocesojudicialupa;
     }
    @Id 
    @GeneratedValue
    @Column(name="IDPROCESOJUDICIALUPA", unique=true, nullable=false)
	public int getIdprocesojudicialupa() {
		return idprocesojudicialupa;
	}
	public void setIdprocesojudicialupa(int idprocesojudicialupa) {
		this.idprocesojudicialupa = idprocesojudicialupa;
	}
    

	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDUPA")
	public Upa getUpa() {
		return upa;
	}

	public void setUpa(Upa upa) {
		this.upa = upa;
	}
	
	
    @Column(name="OBSERVACION", length=1000)
	public String getObservacion() {
		return observacion;
	}
	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}
    @Column(name="EXPEDIENTE", length=100	)
	public String getExpediente() {
		return expediente;
	}
	public void setExpediente(String expediente) {
		this.expediente = expediente;
	}

	@Column(name = "USRCRE", length = 100)
	public String getUsrcre() {
		return this.usrcre;
	}

	public void setUsrcre(String usrcre) {
		this.usrcre = usrcre;
	}

	@Column(name = "USRMOD", length = 100)
	public String getUsrmod() {
		return this.usrmod;
	}

	public void setUsrmod(String usrmod) {
		this.usrmod = usrmod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECCRE", length = 23)
	public Date getFeccre() {
		return this.feccre;
	}

	public void setFeccre(Date feccre) {
		this.feccre = feccre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECMOD", length = 23)
	public Date getFecmod() {
		return this.fecmod;
	}

	public void setFecmod(Date fecmod) {
		this.fecmod = fecmod;
	}
	
	@Column(name="ESTADO")
    public String getEstado() {
		return estado;
	}
	public void setEstado(String estado) {
		this.estado = estado;
	}
	 @Column(name="SIFINALIZADO")
	public Boolean getSifinalizado() {
			return sifinalizado;
		}
		public void setSifinalizado(Boolean sifinalizado) {
			this.sifinalizado = sifinalizado;
		}
	 @Column(name="MOTIVO")
	public String getMotivo() {
		return motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}
	 @Column(name="SITUACION")
	public String getSituacion() {
		return situacion;
	}
	 
	public void setSituacion(String situacion) {
		this.situacion = situacion;
	}
	
	 @Column(name="SIDOCUMENTO")
	public Boolean getSidocumento() {
		return sidocumento;
		}
	public void setSidocumento(Boolean sidocumento) {
		this.sidocumento = sidocumento;
		}
	
	 @Column(name="OBSERVACIONMODIFICACION",length=1000)
	public String getObservacionmodificacion() {
		return observacionmodificacion;
	}

	public void setObservacionmodificacion(String observacionmodificacion) {
		this.observacionmodificacion = observacionmodificacion;
	}
	
	@Column(name="HOST_IP_USRCRE")
	public String getHost_ip_usrcre() {
		return host_ip_usrcre;
	}
	public void setHost_ip_usrcre(String host_ip_usrcre) {
		this.host_ip_usrcre = host_ip_usrcre;
	}
	@Column(name="HOST_IP_USRMOD")
	public String getHost_ip_usrmod() {
		return host_ip_usrmod;
	}
	public void setHost_ip_usrmod(String host_ip_usrmod) {
		this.host_ip_usrmod = host_ip_usrmod;
	}
	
     
     
}


