package pe.gob.sblm.sgi.entity;

// Generated 20/12/2013 11:02:53 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Requisito generated by hbm2java
 */
@Entity
@Table(name = "REQUISITO", schema = "dbo", catalog = "sisinmueble")
public class Requisito implements java.io.Serializable {

	private int idrequisito;
	private Tiporequisito tiporequisito;
	private String descripcion;
	private Set<Detallesegcontrato> detallesegcontratos = new HashSet<Detallesegcontrato>(
			0);

	public Requisito() {
	}

	public Requisito(int idrequisito) {
		this.idrequisito = idrequisito;
	}

	public Requisito(int idrequisito, Tiporequisito tiporequisito,
			String descripcion, Set<Detallesegcontrato> detallesegcontratos) {
		this.idrequisito = idrequisito;
		this.tiporequisito = tiporequisito;
		this.descripcion = descripcion;
		this.detallesegcontratos = detallesegcontratos;
	}

	@Id
	@Column(name = "IDREQUISITO", unique = true, nullable = false)
	public int getIdrequisito() {
		return this.idrequisito;
	}

	public void setIdrequisito(int idrequisito) {
		this.idrequisito = idrequisito;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDTIPOREQUISITO")
	public Tiporequisito getTiporequisito() {
		return this.tiporequisito;
	}

	public void setTiporequisito(Tiporequisito tiporequisito) {
		this.tiporequisito = tiporequisito;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "requisito")
	public Set<Detallesegcontrato> getDetallesegcontratos() {
		return this.detallesegcontratos;
	}

	public void setDetallesegcontratos(
			Set<Detallesegcontrato> detallesegcontratos) {
		this.detallesegcontratos = detallesegcontratos;
	}

}
