package pe.gob.sblm.sgi.entity;
// Generated 20-dic-2015 10:51:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Saneamiento generated by hbm2java
 */
@Entity
@Table(name="SANEAMIENTO"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class Saneamiento  implements java.io.Serializable {


     private int idsaneamiento;
     private String descripcion;
     private Boolean estado;
     private Set<Inmueblesaneamiento> inmueblesaneamientos = new HashSet<Inmueblesaneamiento>(0);

    public Saneamiento() {
    }

	
    public Saneamiento(int idsaneamiento) {
        this.idsaneamiento = idsaneamiento;
    }
    public Saneamiento(int idsaneamiento, String descripcion, Boolean estado, Set<Inmueblesaneamiento> inmueblesaneamientos) {
       this.idsaneamiento = idsaneamiento;
       this.descripcion = descripcion;
       this.estado = estado;
       this.inmueblesaneamientos = inmueblesaneamientos;
    }
   
     @Id 
     @GeneratedValue
    @Column(name="IDSANEAMIENTO", unique=true, nullable=false)
    public int getIdsaneamiento() {
        return this.idsaneamiento;
    }
    
    public void setIdsaneamiento(int idsaneamiento) {
        this.idsaneamiento = idsaneamiento;
    }

    
    @Column(name="DESCRIPCION", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="ESTADO")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="saneamiento")
    public Set<Inmueblesaneamiento> getInmueblesaneamientos() {
        return this.inmueblesaneamientos;
    }
    
    public void setInmueblesaneamientos(Set<Inmueblesaneamiento> inmueblesaneamientos) {
        this.inmueblesaneamientos = inmueblesaneamientos;
    }




}


