package pe.gob.sblm.sgi.entity;
// Generated 19/03/2014 03:10:50 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipointerior generated by hbm2java
 */
@Entity
@Table(name="TIPOINTERIOR"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class Tipointerior  implements java.io.Serializable {


     private int idtipointerior;
     private String descripcion;
     private Boolean estado;
     private Set<Inmueble> inmuebles = new HashSet<Inmueble>(0);

    public Tipointerior() {
    }

	
    public Tipointerior(int idtipointerior) {
        this.idtipointerior = idtipointerior;
    }
    public Tipointerior(int idtipointerior, String descripcion, Boolean estado, Set<Upa> upas, Set<Inmueble> inmuebles) {
       this.idtipointerior = idtipointerior;
       this.descripcion = descripcion;
       this.estado = estado;
       this.inmuebles = inmuebles;
    }
   
     @Id 
    
    @Column(name="IDTIPOINTERIOR", unique=true, nullable=false)
    public int getIdtipointerior() {
        return this.idtipointerior;
    }
    
    public void setIdtipointerior(int idtipointerior) {
        this.idtipointerior = idtipointerior;
    }
    
    @Column(name="DESCRIPCION", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="ESTADO")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tipointerior")
    public Set<Inmueble> getInmuebles() {
        return this.inmuebles;
    }
    
    public void setInmuebles(Set<Inmueble> inmuebles) {
        this.inmuebles = inmuebles;
    }




}


