package pe.gob.sblm.sgi.entity;

// Generated 20/12/2013 05:07:36 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tiporequisito generated by hbm2java
 */
@Entity
@Table(name = "TIPOREQUISITO", schema = "dbo", catalog = "sisinmueble")
public class Tiporequisito implements java.io.Serializable {

	private int idtiporequisito;
	private String descripcion;
	private Boolean estado;
	private Set<Requisito> requisitos = new HashSet<Requisito>(0);

	public Tiporequisito() {
	}

	public Tiporequisito(int idtiporequisito) {
		this.idtiporequisito = idtiporequisito;
	}

	public Tiporequisito(int idtiporequisito, String descripcion,
			Boolean estado, Set<Requisito> requisitos) {
		this.idtiporequisito = idtiporequisito;
		this.descripcion = descripcion;
		this.estado = estado;
		this.requisitos = requisitos;
	}

	@Id
	@Column(name = "IDTIPOREQUISITO", unique = true, nullable = false)
	public int getIdtiporequisito() {
		return this.idtiporequisito;
	}

	public void setIdtiporequisito(int idtiporequisito) {
		this.idtiporequisito = idtiporequisito;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTADO")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tiporequisito")
	public Set<Requisito> getRequisitos() {
		return this.requisitos;
	}

	public void setRequisitos(Set<Requisito> requisitos) {
		this.requisitos = requisitos;
	}

}
