package pe.gob.sblm.sgi.entity;
// Generated 19/03/2014 03:10:50 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tipodocu generated by hbm2java
 */
@Entity
@Table(name="TIPODOCU"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class Tipodocu  implements java.io.Serializable {


     private String idtipodocu;
     private String tipDocu;
     private String usrcre;
     private byte[] usrmod;
     private Date feccre;
     private Date fecmod;
     private String nroDocu;
     private Set<Comprobantepago> comprobantepagos = new HashSet<Comprobantepago>(0);

    
    public Tipodocu() {
		super();
	}
	public Tipodocu(String idtipodocu) {
        this.idtipodocu = idtipodocu;
    }
    public Tipodocu(String idtipodocu, String tipDocu, String usrcre, byte[] usrmod, Date feccre, Date fecmod, String nroDocu, Set<Comprobantepago> comprobantepagos) {
       this.idtipodocu = idtipodocu;
       this.tipDocu = tipDocu;
       this.usrcre = usrcre;
       this.usrmod = usrmod;
       this.feccre = feccre;
       this.fecmod = fecmod;
       this.nroDocu = nroDocu;
       this.comprobantepagos = comprobantepagos;
    }
   
     @Id 
    
    @Column(name="IDTIPODOCU", unique=true, nullable=false, length=2)
    public String getIdtipodocu() {
        return this.idtipodocu;
    }
    
    public void setIdtipodocu(String idtipodocu) {
        this.idtipodocu = idtipodocu;
    }
    
    @Column(name="TIP_DOCU", length=20)
    public String getTipDocu() {
        return this.tipDocu;
    }
    
    public void setTipDocu(String tipDocu) {
        this.tipDocu = tipDocu;
    }
    
    @Column(name="USRCRE", length=50)
    public String getUsrcre() {
        return this.usrcre;
    }
    
    public void setUsrcre(String usrcre) {
        this.usrcre = usrcre;
    }
    
    @Column(name="USRMOD")
    public byte[] getUsrmod() {
        return this.usrmod;
    }
    
    public void setUsrmod(byte[] usrmod) {
        this.usrmod = usrmod;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECCRE", length=23)
    public Date getFeccre() {
        return this.feccre;
    }
    
    public void setFeccre(Date feccre) {
        this.feccre = feccre;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECMOD", length=23)
    public Date getFecmod() {
        return this.fecmod;
    }
    
    public void setFecmod(Date fecmod) {
        this.fecmod = fecmod;
    }
    
    @Column(name="NRO_DOCU", length=10)
    public String getNroDocu() {
        return this.nroDocu;
    }
    
    public void setNroDocu(String nroDocu) {
        this.nroDocu = nroDocu;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tipodocu")
    public Set<Comprobantepago> getComprobantepagos() {
        return this.comprobantepagos;
    }
    
    public void setComprobantepagos(Set<Comprobantepago> comprobantepagos) {
        this.comprobantepagos = comprobantepagos;
    }




}


