package pe.gob.sblm.sgi.entity;
// Generated 19/03/2014 03:10:50 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipotitularidad generated by hbm2java
 */
@Entity
@Table(name="TIPOTITULARIDAD"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class Tipotitularidad  implements java.io.Serializable {


     private int idtipotitularidad;
     private String descripcion;
     private Boolean estado;
     private Set<Inmueble> inmuebles = new HashSet<Inmueble>(0);

    public Tipotitularidad() {
    }

	
    public Tipotitularidad(int idtipotitularidad) {
        this.idtipotitularidad = idtipotitularidad;
    }
    public Tipotitularidad(int idtipotitularidad, String descripcion, Boolean estado, Set<Inmueble> inmuebles) {
       this.idtipotitularidad = idtipotitularidad;
       this.descripcion = descripcion;
       this.estado = estado;
       this.inmuebles = inmuebles;
    }
   
     @Id 
    
    @Column(name="IDTIPOTITULARIDAD", unique=true, nullable=false)
    public int getIdtipotitularidad() {
        return this.idtipotitularidad;
    }
    
    public void setIdtipotitularidad(int idtipotitularidad) {
        this.idtipotitularidad = idtipotitularidad;
    }
    
    @Column(name="DESCRIPCION", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="ESTADO")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tipotitularidad")
    public Set<Inmueble> getInmuebles() {
        return this.inmuebles;
    }
    
    public void setInmuebles(Set<Inmueble> inmuebles) {
        this.inmuebles = inmuebles;
    }




}


