package pe.gob.sblm.sgi.entity;
// Generated 19/03/2014 03:10:50 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipomovimiento generated by hbm2java
 */
@Entity
@Table(name="TIPOCONCEPTO"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class Tipoconcepto  implements java.io.Serializable {


     private String idtipoconcepto;
     private String descripcion;
     private Boolean estado;


	
   
    public Tipoconcepto() {
		super();
	}

	public Tipoconcepto(String idtipoconcepto) {
		super();
		this.idtipoconcepto = idtipoconcepto;
	}
    
	@Id 
    @Column(name="IDTIPOCONCEPTO", unique=true, nullable=false, length=2)
     public String getIdtipoconcepto() {
 		return idtipoconcepto;
 	}
 	public void setIdtipoconcepto(String idtipoconcepto) {
 		this.idtipoconcepto = idtipoconcepto;
 	}
    
    @Column(name="DESCRIPCION", length=20)
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
    public String getDescripcion() {
		return descripcion;
	}

    @Column(name="ESTADO", length=20)
	public Boolean getEstado() {
		return estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}
    
}


