package pe.gob.sblm.sgi.entity;
// Generated 19/03/2014 03:10:50 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Titularidad generated by hbm2java
 */
@Entity
@Table(name="TITULARIDAD"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class Titularidad  implements java.io.Serializable {


     private int idtitularidad;
     private String nombre;
     private String descripcion;
     private Boolean estado;
     private Tipotitularidad tipotitularidad;
     private Set<Inmueble> inmuebles = new HashSet<Inmueble>(0);

    public Titularidad() {
    }

	
    public Titularidad(int idtitularidad) {
        this.idtitularidad = idtitularidad;
    }
    public Titularidad(int idtitularidad, String nombre, String descripcion, Boolean estado, Set<Inmueble> inmuebles) {
       this.idtitularidad = idtitularidad;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estado = estado;
       this.inmuebles = inmuebles;
    }
   
     @Id 
    
    @Column(name="IDTITULARIDAD", unique=true, nullable=false)
    public int getIdtitularidad() {
        return this.idtitularidad;
    }
    
    public void setIdtitularidad(int idtitularidad) {
        this.idtitularidad = idtitularidad;
    }
    
    @Column(name="NOMBRE", length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="DESCRIPCION", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="ESTADO")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IDTIPOTITULARIDAD")
	public Tipotitularidad getTipotitularidad() {
		return tipotitularidad;
	}


	public void setTipotitularidad(Tipotitularidad tipotitularidad) {
		this.tipotitularidad = tipotitularidad;
	}

   

    
   




}


