package pe.gob.sblm.sgi.entity;
// Generated 19/03/2014 03:10:50 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Upa generated by hbm2java
 */
@Entity
@Table(name="UPA"
    ,schema="dbo"
    ,catalog="sisinmueble"
)
public class Upa  implements java.io.Serializable {


     private int idupa;
     private Inmueble inmueble;
     private String clave;
     private String direccion;
     private String nombrevia;
     private String numprincipal;
     private String numgrupal;
     private String manzana;
     private String lote;
     private String sublote;
     private String nombrenuminterior;
     private String nombrenumzona;
     private String nombrenumsector;
     private String nombrenumetapa;
     private String referenciaupa;
     private String nombrehabilitacionurbana;
     private Boolean opcagua;
     private Boolean opcdesague;
     private BigDecimal areaterreno;
     private BigDecimal areaconstruida;
     private BigDecimal areacomun;
     private BigDecimal arealibre;
     private BigDecimal areadeclarada;
     private String obsupa;
     private Boolean opcparteinmueble;
     private Boolean opcupadisponible;
     private Boolean opcupadepurada;
     private Boolean opcupahabilitada;
     private String usrcre;
     private String usrmod;
     private Date feccre;
     private Date fecmod;
     private BigDecimal mercedconductiva;
     private String etapa;
     private String antiguedad;
     private String conservacion;
     private Date fechavaluacion;
     private String ubicacionpiso;
     private String obsupaotros;
     private Boolean habilitacionurbana;
     private String idenantiguedadupa;
     private String idenestadoconservacionupa;
     private String idenmaterialestrucpredom;
     private String identipohabilitacionurbana;
     private String idenusoupa;
     private String mep;
     private String uso;
     private String tipovia;
     private String tipointerior;
     private String valuacion;
     private String tugurizadoruinoso;
     private Boolean siprocesojudicial;
//     private String tipotitularidad;
//     private String materialPredominante;
     private String observacionprocesojudicial;
     private Boolean sicopropiedad;
     private String observacioncopropiedad;
     private String  clavenueva;
     private String  obs_mod;
     private Upa idupa_anterior;
     private String  observacion;
     private String  estado;
     private Boolean siactualizaclave;
     //private Integer idinmueblemaestro;
     private Inmueblemaestro inmueblemaestro;
     
     
     private Set<Contrato> contratos = new HashSet<Contrato>(0);
     private Set<Arbitrio> arbitrios = new HashSet<Arbitrio>(0);

    public Upa() {
    }

	
    public Upa(int idupa) {
        this.idupa = idupa;
    }
    public Upa(int idupa, Tipovia tipovia, Inmueble inmueble, Valuacion valuacion, Uso uso, Tipointerior tipointerior, Mep mep, String clave, String direccion, String nombrevia, String numprincipal, String numgrupal, String manzana, String lote, String sublote, String nombrenuminterior, String nombrenumzona, String nombrenumsector, String nombrenumetapa, String referenciaupa, String nombrehabilitacionurbana, Boolean opcagua, Boolean opcdesague, BigDecimal areaterreno, BigDecimal areaconstruida, BigDecimal areacomun, BigDecimal arealibre, BigDecimal areadeclarada, String obsupa, Boolean opcparteinmueble, Boolean opcupadisponible, Boolean opcupadepurada, Boolean opcupahabilitada, String usrcre, String usrmod, Date feccre, Date fecmod, BigDecimal mercedconductiva, String etapa, String antiguedad, String conservacion, Date fechavaluacion, String ubicacionpiso, String obsupaotros, Boolean habilitacionurbana, String idenantiguedadupa, String idenestadoconservacionupa, String idenmaterialestrucpredom, String identipohabilitacionurbana, String idenusoupa, Set<Contrato> contratos) {
       System.out.println("CONSTRUCTOR=");
       this.idupa = idupa;
       this.inmueble = inmueble;
       this.clave = clave;
       this.direccion = direccion;
       this.nombrevia = nombrevia;
       this.numprincipal = numprincipal;
       this.numgrupal = numgrupal;
       this.manzana = manzana;
       this.lote = lote;
       this.sublote = sublote;
       this.nombrenuminterior = nombrenuminterior;
       this.nombrenumzona = nombrenumzona;
       this.nombrenumsector = nombrenumsector;
       this.nombrenumetapa = nombrenumetapa;
       this.referenciaupa = referenciaupa;
       this.nombrehabilitacionurbana = nombrehabilitacionurbana;
       this.opcagua = opcagua;
       this.opcdesague = opcdesague;
       this.areaterreno = areaterreno;
       this.areaconstruida = areaconstruida;
       this.areacomun = areacomun;
       this.arealibre = arealibre;
       this.areadeclarada = areadeclarada;
       this.obsupa = obsupa;
       this.opcparteinmueble = opcparteinmueble;
       this.opcupadisponible = opcupadisponible;
       this.opcupadepurada = opcupadepurada;
       this.opcupahabilitada = opcupahabilitada;
       this.usrcre = usrcre;
       this.usrmod = usrmod;
       this.feccre = feccre;
       this.fecmod = fecmod;
       this.mercedconductiva = mercedconductiva;
       this.etapa = etapa;
       this.antiguedad = antiguedad;
       this.conservacion = conservacion;
       this.fechavaluacion = fechavaluacion;
       this.ubicacionpiso = ubicacionpiso;
       this.obsupaotros = obsupaotros;
       this.habilitacionurbana = habilitacionurbana;
       this.idenantiguedadupa = idenantiguedadupa;
       this.idenestadoconservacionupa = idenestadoconservacionupa;
       this.idenmaterialestrucpredom = idenmaterialestrucpredom;
       this.identipohabilitacionurbana = identipohabilitacionurbana;
       this.idenusoupa = idenusoupa;
       this.contratos = contratos;
    }
   
     @Id 
     @GeneratedValue
    @Column(name="IDUPA", unique=true, nullable=false)
    public int getIdupa() {
        return this.idupa;
    }
    
    public void setIdupa(int idupa) {
        this.idupa = idupa;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDINMUEBLE")
    public Inmueble getInmueble() {
        return this.inmueble;
    }
    
    public void setInmueble(Inmueble inmueble) {
        this.inmueble = inmueble;
    }
    
    @Column(name="CLAVE", length=14)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    
    @Column(name="DIRECCION", length=100)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="NOMBREVIA", length=100)
    public String getNombrevia() {
        return this.nombrevia;
    }
    
    public void setNombrevia(String nombrevia) {
        this.nombrevia = nombrevia;
    }
    
    @Column(name="NUMPRINCIPAL", length=50)
    public String getNumprincipal() {
        return this.numprincipal;
    }
    
    public void setNumprincipal(String numprincipal) {
        this.numprincipal = numprincipal;
    }
    
    @Column(name="NUMGRUPAL", length=50)
    public String getNumgrupal() {
        return this.numgrupal;
    }
    
    public void setNumgrupal(String numgrupal) {
        this.numgrupal = numgrupal;
    }
    
    @Column(name="MANZANA", length=10)
    public String getManzana() {
        return this.manzana;
    }
    
    public void setManzana(String manzana) {
        this.manzana = manzana;
    }
    
    @Column(name="LOTE", length=10)
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }
    
    @Column(name="SUBLOTE", length=10)
    public String getSublote() {
        return this.sublote;
    }
    
    public void setSublote(String sublote) {
        this.sublote = sublote;
    }
    
    @Column(name="NOMBRENUMINTERIOR", length=100)
    public String getNombrenuminterior() {
        return this.nombrenuminterior;
    }
    
    public void setNombrenuminterior(String nombrenuminterior) {
        this.nombrenuminterior = nombrenuminterior;
    }
    
    @Column(name="NOMBRENUMZONA", length=20)
    public String getNombrenumzona() {
        return this.nombrenumzona;
    }
    
    public void setNombrenumzona(String nombrenumzona) {
        this.nombrenumzona = nombrenumzona;
    }
    
    @Column(name="NOMBRENUMSECTOR", length=20)
    public String getNombrenumsector() {
        return this.nombrenumsector;
    }
    
    public void setNombrenumsector(String nombrenumsector) {
        this.nombrenumsector = nombrenumsector;
    }
    
    @Column(name="NOMBRENUMETAPA", length=20)
    public String getNombrenumetapa() {
        return this.nombrenumetapa;
    }
    
    public void setNombrenumetapa(String nombrenumetapa) {
        this.nombrenumetapa = nombrenumetapa;
    }
    
    @Column(name="REFERENCIAUPA", length=100)
    public String getReferenciaupa() {
        return this.referenciaupa;
    }
    
    public void setReferenciaupa(String referenciaupa) {
        this.referenciaupa = referenciaupa;
    }
    
    @Column(name="NOMBREHABILITACIONURBANA", length=100)
    public String getNombrehabilitacionurbana() {
        return this.nombrehabilitacionurbana;
    }
    
    public void setNombrehabilitacionurbana(String nombrehabilitacionurbana) {
        this.nombrehabilitacionurbana = nombrehabilitacionurbana;
    }
    
    @Column(name="OPCAGUA")
    public Boolean getOpcagua() {
        return this.opcagua;
    }
    
    public void setOpcagua(Boolean opcagua) {
        this.opcagua = opcagua;
    }
    
    @Column(name="OPCDESAGUE")
    public Boolean getOpcdesague() {
        return this.opcdesague;
    }
    
    public void setOpcdesague(Boolean opcdesague) {
        this.opcdesague = opcdesague;
    }
    
    @Column(name="AREATERRENO", precision=9)
    public BigDecimal getAreaterreno() {
        return this.areaterreno;
    }
    
    public void setAreaterreno(BigDecimal areaterreno) {
        this.areaterreno = areaterreno;
    }
    
    @Column(name="AREACONSTRUIDA", precision=9)
    public BigDecimal getAreaconstruida() {
        return this.areaconstruida;
    }
    
    public void setAreaconstruida(BigDecimal areaconstruida) {
        this.areaconstruida = areaconstruida;
    }
    
    @Column(name="AREACOMUN", precision=9)
    public BigDecimal getAreacomun() {
        return this.areacomun;
    }
    
    public void setAreacomun(BigDecimal areacomun) {
        this.areacomun = areacomun;
    }
    
    @Column(name="AREALIBRE", precision=9)
    public BigDecimal getArealibre() {
        return this.arealibre;
    }
    
    public void setArealibre(BigDecimal arealibre) {
        this.arealibre = arealibre;
    }
    
    @Column(name="AREADECLARADA", precision=9)
    public BigDecimal getAreadeclarada() {
        return this.areadeclarada;
    }
    
    public void setAreadeclarada(BigDecimal areadeclarada) {
        this.areadeclarada = areadeclarada;
    }
    
    @Column(name="OBSUPA", length=200)
    public String getObsupa() {
        return this.obsupa;
    }
    
    public void setObsupa(String obsupa) {
        this.obsupa = obsupa;
    }
    
    @Column(name="OPCPARTEINMUEBLE")
    public Boolean getOpcparteinmueble() {
        return this.opcparteinmueble;
    }
    
    public void setOpcparteinmueble(Boolean opcparteinmueble) {
        this.opcparteinmueble = opcparteinmueble;
    }
    
    @Column(name="OPCUPADISPONIBLE")
    public Boolean getOpcupadisponible() {
        return this.opcupadisponible;
    }
    
    public void setOpcupadisponible(Boolean opcupadisponible) {
        this.opcupadisponible = opcupadisponible;
    }
    
    @Column(name="OPCUPADEPURADA")
    public Boolean getOpcupadepurada() {
        return this.opcupadepurada;
    }
    
    public void setOpcupadepurada(Boolean opcupadepurada) {
        this.opcupadepurada = opcupadepurada;
    }
    
    @Column(name="OPCUPAHABILITADA")
    public Boolean getOpcupahabilitada() {
        return this.opcupahabilitada;
    }
    
    public void setOpcupahabilitada(Boolean opcupahabilitada) {
        this.opcupahabilitada = opcupahabilitada;
    }
    
    @Column(name="USRCRE", length=100)
    public String getUsrcre() {
        return this.usrcre;
    }
    
    public void setUsrcre(String usrcre) {
        this.usrcre = usrcre;
    }
    
    @Column(name="USRMOD", length=100)
    public String getUsrmod() {
        return this.usrmod;
    }
    
    public void setUsrmod(String usrmod) {
        this.usrmod = usrmod;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECCRE", length=23)
    public Date getFeccre() {
        return this.feccre;
    }
    
    public void setFeccre(Date feccre) {
        this.feccre = feccre;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECMOD", length=23)
    public Date getFecmod() {
        return this.fecmod;
    }
    
    public void setFecmod(Date fecmod) {
        this.fecmod = fecmod;
    }
    
    @Column(name="MERCEDCONDUCTIVA", precision=9)
    public BigDecimal getMercedconductiva() {
        return this.mercedconductiva;
    }
    
    public void setMercedconductiva(BigDecimal mercedconductiva) {
        this.mercedconductiva = mercedconductiva;
    }
    
    @Column(name="ETAPA", length=50)
    public String getEtapa() {
        return this.etapa;
    }
    
    public void setEtapa(String etapa) {
        this.etapa = etapa;
    }
    
    @Column(name="ANTIGUEDAD", length=50)
    public String getAntiguedad() {
        return this.antiguedad;
    }
    
    public void setAntiguedad(String antiguedad) {
        this.antiguedad = antiguedad;
    }
    
    @Column(name="CONSERVACION", length=50)
    public String getConservacion() {
        return this.conservacion;
    }
    
    public void setConservacion(String conservacion) {
        this.conservacion = conservacion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAVALUACION", length=23)
    public Date getFechavaluacion() {
        return this.fechavaluacion;
    }
    
    public void setFechavaluacion(Date fechavaluacion) {
        this.fechavaluacion = fechavaluacion;
    }
    
    @Column(name="UBICACIONPISO", length=10)
    public String getUbicacionpiso() {
        return this.ubicacionpiso;
    }
    
    public void setUbicacionpiso(String ubicacionpiso) {
        this.ubicacionpiso = ubicacionpiso;
    }
    
    @Column(name="OBSUPAOTROS", length=200)
    public String getObsupaotros() {
        return this.obsupaotros;
    }
    
    public void setObsupaotros(String obsupaotros) {
        this.obsupaotros = obsupaotros;
    }
    
    @Column(name="HABILITACIONURBANA")
    public Boolean getHabilitacionurbana() {
        return this.habilitacionurbana;
    }
    
    public void setHabilitacionurbana(Boolean habilitacionurbana) {
        this.habilitacionurbana = habilitacionurbana;
    }
    
    
    
    @Column(name="SIPROCESOJUDICIAL")   
    public Boolean getSiprocesojudicial() {
		return siprocesojudicial;
	}

	public void setSiprocesojudicial(Boolean siprocesojudicial) {
		this.siprocesojudicial = siprocesojudicial;
	}


	@Column(name="IDENANTIGUEDADUPA", length=10)
    public String getIdenantiguedadupa() {
        return this.idenantiguedadupa;
    }
    
    public void setIdenantiguedadupa(String idenantiguedadupa) {
        this.idenantiguedadupa = idenantiguedadupa;
    }
    
    @Column(name="IDENESTADOCONSERVACIONUPA", length=10)
    public String getIdenestadoconservacionupa() {
        return this.idenestadoconservacionupa;
    }
    
    public void setIdenestadoconservacionupa(String idenestadoconservacionupa) {
        this.idenestadoconservacionupa = idenestadoconservacionupa;
    }
    
    @Column(name="IDENMATERIALESTRUCPREDOM", length=10)
    public String getIdenmaterialestrucpredom() {
        return this.idenmaterialestrucpredom;
    }
    
    public void setIdenmaterialestrucpredom(String idenmaterialestrucpredom) {
        this.idenmaterialestrucpredom = idenmaterialestrucpredom;
    }
    
    @Column(name="IDENTIPOHABILITACIONURBANA", length=10)
    public String getIdentipohabilitacionurbana() {
        return this.identipohabilitacionurbana;
    }
    
    public void setIdentipohabilitacionurbana(String identipohabilitacionurbana) {
        this.identipohabilitacionurbana = identipohabilitacionurbana;
    }
    
    
    @Column(name="MEP", length=50) 
    public String getMep() {
		return mep;
	}


	public void setMep(String mep) {
		this.mep = mep;
	}

	@Column(name="USO", length=50)
	public String getUso() {
		return uso;
	}


	public void setUso(String uso) {
		this.uso = uso;
	}

	@Column(name="TIPOVIA", length=50)
	public String getTipovia() {
		return tipovia;
	}


	public void setTipovia(String tipovia) {
		this.tipovia = tipovia;
	}

	@Column(name="TIPOINTERIOR", length=50)
	public String getTipointerior() {
		return tipointerior;
	}


	public void setTipointerior(String tipointerior) {
		this.tipointerior = tipointerior;
	}
  	
	@Column(name="VALUACION", length=50)
	public String getValuacion() {
		return valuacion;
	}

	public void setValuacion(String valuacion) {
		this.valuacion = valuacion;
	}

	@Column(name="TUGURIZADORUINOSO", length=50)
	public String getTugurizadoruinoso() {
		return tugurizadoruinoso;
	}


	public void setTugurizadoruinoso(String tugurizadoruinoso) {
		this.tugurizadoruinoso = tugurizadoruinoso;
	}


	@Column(name="IDENUSOUPA", length=10)
    public String getIdenusoupa() {
        return this.idenusoupa;
    }
    
    public void setIdenusoupa(String idenusoupa) {
        this.idenusoupa = idenusoupa;
    }
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="upa")
    public Set<Contrato> getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set<Contrato> contratos) {
        this.contratos = contratos;
    }

    @Column(name="OBSERVACIONPROCESOJUDICIAL", length=200)
	public String getObservacionprocesojudicial() {
		return observacionprocesojudicial;
	}


	public void setObservacionprocesojudicial(String observacionprocesojudicial) {
		this.observacionprocesojudicial = observacionprocesojudicial;
	}

	@Column(name="SICOPROPIEDAD") 
	public Boolean getSicopropiedad() {
		return sicopropiedad;
	}


	public void setSicopropiedad(Boolean sicopropiedad) {
		this.sicopropiedad = sicopropiedad;
	}

	@Column(name="OBSERVACIONCOPROPIEDAD", length=200)
	public String getObservacioncopropiedad() {
		return observacioncopropiedad;
	}


	public void setObservacioncopropiedad(String observacioncopropiedad) {
		this.observacioncopropiedad = observacioncopropiedad;
	}

	@Column(name="CLAVENUEVA")
    public String getClavenueva() {
		return clavenueva;
	}


	public void setClavenueva(String clavenueva) {
		this.clavenueva = clavenueva;
	}


    @Column(name="OBS_MOD" ,length=300)
	public String getObs_mod() {
		return obs_mod;
	}


	public void setObs_mod(String obs_mod) {
		this.obs_mod = obs_mod;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="IDUPA_ANTERIOR")
	public Upa getIdupa_anterior() {
		return idupa_anterior;
	}


	public void setIdupa_anterior(Upa idupa_anterior) {
		this.idupa_anterior = idupa_anterior;
	}

    @Column(name="OBSERVACION" , length=300)
	public String getObservacion() {
		return observacion;
	}


	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

    @Column(name="ESTADO" ,length=10)
	public String getEstado() {
		return estado;
	}


	public void setEstado(String estado) {
		this.estado = estado;
	}

    @Column(name="SIACTUALIZACLAVE")
	public Boolean getSiactualizaclave() {
		return siactualizaclave;
	}


	public void setSiactualizaclave(Boolean siactualizaclave) {
		this.siactualizaclave = siactualizaclave;
	}
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDINMUEBLEMAESTRO")
	public Inmueblemaestro getInmueblemaestro() {
		return inmueblemaestro;
	}


	public void setInmueblemaestro(Inmueblemaestro inmueblemaestro) {
		this.inmueblemaestro = inmueblemaestro;
	}

	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="upa")
	public Set<Arbitrio> getArbitrios() {
		return arbitrios;
	}


	public void setArbitrios(Set<Arbitrio> arbitrios) {
		this.arbitrios = arbitrios;
	}

//	@Column(name="IDINMUEBLEMAESTRO")
//	public Integer getIdinmueblemaestro() {
//		return idinmueblemaestro;
//	}
//
//
//	public void setIdinmueblemaestro(Integer idinmueblemaestro) {
//		this.idinmueblemaestro = idinmueblemaestro;
//	}
	

}


